// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workspace Sidebar Item is the type-safe Go struct generated from the Workspace Sidebar Item GoType.
type Workspace Sidebar Item struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Type string `json:"type" db:"type"`
	Label string `json:"label" db:"label"`
	LinkType string `json:"link_type" db:"link_type"`
	LinkTo string `json:"link_to" db:"link_to"`
	Icon string `json:"icon" db:"icon"`
	Child int `json:"child" db:"child"`
	Indent int `json:"indent" db:"indent"`
	Collapsible int `json:"collapsible" db:"collapsible"`
	DetailsSection string `json:"details_section" db:"details_section"`
	ColumnBreakKrzu string `json:"column_break_krzu" db:"column_break_krzu"`
	DisplaySection string `json:"display_section" db:"display_section"`
	CollapsibleColumn string `json:"collapsible_column" db:"collapsible_column"`
	KeepClosed int `json:"keep_closed" db:"keep_closed"`
	ColumnBreakJexf string `json:"column_break_jexf" db:"column_break_jexf"`
	Url string `json:"url" db:"url"`
	ShowArrow int `json:"show_arrow" db:"show_arrow"`
	SectionBreakWhjq string `json:"section_break_whjq" db:"section_break_whjq"`
	Filters string `json:"filters" db:"filters"`
	RouteOptions string `json:"route_options" db:"route_options"`
	NavigateToTab string `json:"navigate_to_tab" db:"navigate_to_tab"`
	FilterArea string `json:"filter_area" db:"filter_area"`
}
