// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Comment is the type-safe Go struct generated from the Comment GoType.
type Comment struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	CommentType string `json:"comment_type" db:"comment_type"`
	CommentEmail string `json:"comment_email" db:"comment_email"`
	Subject string `json:"subject" db:"subject"`
	CommentBy string `json:"comment_by" db:"comment_by"`
	Published int `json:"published" db:"published"`
	Seen int `json:"seen" db:"seen"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceName string `json:"reference_name" db:"reference_name"`
	ReferenceOwner string `json:"reference_owner" db:"reference_owner"`
	SectionBreak10 string `json:"section_break_10" db:"section_break_10"`
	Content string `json:"content" db:"content"`
	IpAddress string `json:"ip_address" db:"ip_address"`
}
