// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// OAuth Bearer Token is the type-safe Go struct generated from the OAuth Bearer Token GoType.
type OAuth Bearer Token struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Client string `json:"client" db:"client"`
	User string `json:"user" db:"user"`
	Scopes string `json:"scopes" db:"scopes"`
	AccessToken string `json:"access_token" db:"access_token"`
	RefreshToken string `json:"refresh_token" db:"refresh_token"`
	ExpirationTime string `json:"expiration_time" db:"expiration_time"`
	ExpiresIn int `json:"expires_in" db:"expires_in"`
	Status string `json:"status" db:"status"`
}
