// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Event Participants is the type-safe Go struct generated from the Event Participants GoType.
type Event Participants struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceDocname string `json:"reference_docname" db:"reference_docname"`
	Email string `json:"email" db:"email"`
	Attending string `json:"attending" db:"attending"`
}
