// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Scheduled Job Type is the type-safe Go struct generated from the Scheduled Job Type GoType.
type Scheduled Job Type struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Method string `json:"method" db:"method"`
	Stopped int `json:"stopped" db:"stopped"`
	CreateLog int `json:"create_log" db:"create_log"`
	LastExecution string `json:"last_execution" db:"last_execution"`
	CronFormat string `json:"cron_format" db:"cron_format"`
	Frequency string `json:"frequency" db:"frequency"`
	ServerScript string `json:"server_script" db:"server_script"`
	NextExecution string `json:"next_execution" db:"next_execution"`
	StatusSection string `json:"status_section" db:"status_section"`
	ColumnBreak9 string `json:"column_break_9" db:"column_break_9"`
	SchedulerEvent string `json:"scheduler_event" db:"scheduler_event"`
}
