// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Print Heading is the type-safe Go struct generated from the Print Heading GoType.
type Print Heading struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	PrintHeading string `json:"print_heading" db:"print_heading"`
	Description string `json:"description" db:"description"`
}
