// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Dashboard Chart Source is the type-safe Go struct generated from the Dashboard Chart Source GoType.
type Dashboard Chart Source struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SourceName string `json:"source_name" db:"source_name"`
	Module string `json:"module" db:"module"`
	Timeseries int `json:"timeseries" db:"timeseries"`
}
