// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Communication Link is the type-safe Go struct generated from the Communication Link GoType.
type Communication Link struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	LinkDoctype string `json:"link_doctype" db:"link_doctype"`
	LinkName string `json:"link_name" db:"link_name"`
	LinkTitle string `json:"link_title" db:"link_title"`
	CommunicationDate string `json:"communication_date" db:"communication_date"`
}
