// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Web Template is the type-safe Go struct generated from the Web Template GoType.
type Web Template struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Template string `json:"template" db:"template"`
	Fields string `json:"fields" db:"fields"`
	Standard int `json:"standard" db:"standard"`
	Type string `json:"type" db:"type"`
	Module string `json:"module" db:"module"`
}
