// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Installed Application is the type-safe Go struct generated from the Installed Application GoType.
type Installed Application struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	GitBranch string `json:"git_branch" db:"git_branch"`
	AppName string `json:"app_name" db:"app_name"`
	AppVersion string `json:"app_version" db:"app_version"`
	HasSetupWizard int `json:"has_setup_wizard" db:"has_setup_wizard"`
	IsSetupComplete int `json:"is_setup_complete" db:"is_setup_complete"`
}
