// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workspace Custom Block is the type-safe Go struct generated from the Workspace Custom Block GoType.
type Workspace Custom Block struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	CustomBlockName string `json:"custom_block_name" db:"custom_block_name"`
	Label string `json:"label" db:"label"`
}
