// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Country is the type-safe Go struct generated from the Country GoType.
type Country struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	CountryName string `json:"country_name" db:"country_name"`
	DateFormat string `json:"date_format" db:"date_format"`
	TimeFormat string `json:"time_format" db:"time_format"`
	TimeZones string `json:"time_zones" db:"time_zones"`
	Code string `json:"code" db:"code"`
}
