// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Personal Data Deletion Step is the type-safe Go struct generated from the Personal Data Deletion Step GoType.
type Personal Data Deletion Step struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
	Status string `json:"status" db:"status"`
	Partial int `json:"partial" db:"partial"`
	Fields string `json:"fields" db:"fields"`
	FilteredBy string `json:"filtered_by" db:"filtered_by"`
}
