// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Log Settings is the type-safe Go struct generated from the Log Settings GoType.
type Log Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	LogsToClear string `json:"logs_to_clear" db:"logs_to_clear"`
}
