// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// User Document Type is the type-safe Go struct generated from the User Document Type GoType.
type User Document Type struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
	PermissionsSection string `json:"permissions_section" db:"permissions_section"`
	Read int `json:"read" db:"read"`
	Write int `json:"write" db:"write"`
	Create int `json:"create" db:"create"`
	ColumnBreak2 string `json:"column_break_2" db:"column_break_2"`
	IsCustom int `json:"is_custom" db:"is_custom"`
	ColumnBreak8 string `json:"column_break_8" db:"column_break_8"`
	Submit int `json:"submit" db:"submit"`
	Cancel int `json:"cancel" db:"cancel"`
	Amend int `json:"amend" db:"amend"`
	Delete int `json:"delete" db:"delete"`
	AdditionalPermissionsSection string `json:"additional_permissions_section" db:"additional_permissions_section"`
	Email int `json:"email" db:"email"`
	ColumnBreakFjuk string `json:"column_break_fjuk" db:"column_break_fjuk"`
	Share int `json:"share" db:"share"`
	Print int `json:"print" db:"print"`
}
