// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Recorder Event is the type-safe Go struct generated from the Recorder Event GoType.
type Recorder Event struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Label string `json:"label" db:"label"`
	RefDoctype string `json:"ref_doctype" db:"ref_doctype"`
	RefName string `json:"ref_name" db:"ref_name"`
	Apps string `json:"apps" db:"apps"`
	Queries int `json:"queries" db:"queries"`
	Duration float64 `json:"duration" db:"duration"`
	Method string `json:"method" db:"method"`
	Depth int `json:"depth" db:"depth"`
	Seq int `json:"seq" db:"seq"`
	Handlers string `json:"handlers" db:"handlers"`
}
