// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Console Log is the type-safe Go struct generated from the Console Log GoType.
type Console Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Script string `json:"script" db:"script"`
	Type string `json:"type" db:"type"`
	Committed int `json:"committed" db:"committed"`
}
