// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// UTM Campaign is the type-safe Go struct generated from the UTM Campaign GoType.
type UTM Campaign struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	CampaignDescription string `json:"campaign_description" db:"campaign_description"`
	Slug string `json:"slug" db:"slug"`
}
