// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Print Style is the type-safe Go struct generated from the Print Style GoType.
type Print Style struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	PrintStyleName string `json:"print_style_name" db:"print_style_name"`
	Disabled int `json:"disabled" db:"disabled"`
	Standard int `json:"standard" db:"standard"`
	Css string `json:"css" db:"css"`
	Preview string `json:"preview" db:"preview"`
}
