// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DocType State is the type-safe Go struct generated from the DocType State GoType.
type DocType State struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	Color string `json:"color" db:"color"`
	Custom int `json:"custom" db:"custom"`
}
