// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// SMS Parameter is the type-safe Go struct generated from the SMS Parameter GoType.
type SMS Parameter struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Parameter string `json:"parameter" db:"parameter"`
	Value string `json:"value" db:"value"`
	Header int `json:"header" db:"header"`
}
