// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Global Search DocType is the type-safe Go struct generated from the Global Search DocType GoType.
type Global Search DocType struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
	Configure string `json:"configure" db:"configure"`
}
