// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Letter Head is the type-safe Go struct generated from the Letter Head GoType.
type Letter Head struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	LetterHeadName string `json:"letter_head_name" db:"letter_head_name"`
	Source string `json:"source" db:"source"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	Disabled int `json:"disabled" db:"disabled"`
	IsDefault int `json:"is_default" db:"is_default"`
	LetterHeadImageSection string `json:"letter_head_image_section" db:"letter_head_image_section"`
	Image string `json:"image" db:"image"`
	HeaderSection string `json:"header_section" db:"header_section"`
	Content string `json:"content" db:"content"`
	FooterSection string `json:"footer_section" db:"footer_section"`
	Footer string `json:"footer" db:"footer"`
	Align string `json:"align" db:"align"`
	ImageHeight float64 `json:"image_height" db:"image_height"`
	ImageWidth float64 `json:"image_width" db:"image_width"`
	FooterImageSection string `json:"footer_image_section" db:"footer_image_section"`
	FooterImage string `json:"footer_image" db:"footer_image"`
	FooterImageHeight float64 `json:"footer_image_height" db:"footer_image_height"`
	FooterImageWidth float64 `json:"footer_image_width" db:"footer_image_width"`
	FooterAlign string `json:"footer_align" db:"footer_align"`
	FooterSource string `json:"footer_source" db:"footer_source"`
	HeaderScript string `json:"header_script" db:"header_script"`
	FooterScript string `json:"footer_script" db:"footer_script"`
	ScriptsSection string `json:"scripts_section" db:"scripts_section"`
	Instructions string `json:"instructions" db:"instructions"`
}
