// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Bulk Update is the type-safe Go struct generated from the Bulk Update GoType.
type Bulk Update struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
	Field string `json:"field" db:"field"`
	UpdateValue string `json:"update_value" db:"update_value"`
	Condition string `json:"condition" db:"condition"`
	Limit int `json:"limit" db:"limit"`
}
