// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Website Slideshow is the type-safe Go struct generated from the Website Slideshow GoType.
type Website Slideshow struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SlideshowName string `json:"slideshow_name" db:"slideshow_name"`
	Sb0 string `json:"sb0" db:"sb0"`
	SlideshowItems string `json:"slideshow_items" db:"slideshow_items"`
	Header string `json:"header" db:"header"`
}
