// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Contact Us Settings is the type-safe Go struct generated from the Contact Us Settings GoType.
type Contact Us Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	IntroductionSection string `json:"introduction_section" db:"introduction_section"`
	ForwardToEmail string `json:"forward_to_email" db:"forward_to_email"`
	Heading string `json:"heading" db:"heading"`
	Introduction string `json:"introduction" db:"introduction"`
	QueryOptions string `json:"query_options" db:"query_options"`
	Address string `json:"address" db:"address"`
	AddressTitle string `json:"address_title" db:"address_title"`
	AddressLine1 string `json:"address_line1" db:"address_line1"`
	AddressLine2 string `json:"address_line2" db:"address_line2"`
	City string `json:"city" db:"city"`
	State string `json:"state" db:"state"`
	Pincode string `json:"pincode" db:"pincode"`
	Country string `json:"country" db:"country"`
	ColumnBreak14 string `json:"column_break_14" db:"column_break_14"`
	Phone string `json:"phone" db:"phone"`
	EmailId string `json:"email_id" db:"email_id"`
	Skype string `json:"skype" db:"skype"`
	IsDisabled int `json:"is_disabled" db:"is_disabled"`
	SendAcknowledgementEmail int `json:"send_acknowledgement_email" db:"send_acknowledgement_email"`
}
