// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Color is the type-safe Go struct generated from the Color GoType.
type Color struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Color string `json:"color" db:"color"`
}
