// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Reply To Address is the type-safe Go struct generated from the Reply To Address GoType.
type Reply To Address struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Name string `json:"_name" db:"_name"`
	ColumnBreakXtxq string `json:"column_break_xtxq" db:"column_break_xtxq"`
	Email string `json:"email" db:"email"`
}
