// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workspace Shortcut is the type-safe Go struct generated from the Workspace Shortcut GoType.
type Workspace Shortcut struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Type string `json:"type" db:"type"`
	LinkTo string `json:"link_to" db:"link_to"`
	DocView string `json:"doc_view" db:"doc_view"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	Label string `json:"label" db:"label"`
	Icon string `json:"icon" db:"icon"`
	RestrictToDomain string `json:"restrict_to_domain" db:"restrict_to_domain"`
	SectionBreak5 string `json:"section_break_5" db:"section_break_5"`
	StatsFilter string `json:"stats_filter" db:"stats_filter"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	Color string `json:"color" db:"color"`
	Format string `json:"format" db:"format"`
	Url string `json:"url" db:"url"`
	KanbanBoard string `json:"kanban_board" db:"kanban_board"`
	ReportRefDoctype string `json:"report_ref_doctype" db:"report_ref_doctype"`
}
