// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// new-doctype-2 is the type-safe Go struct generated from the new-doctype-2 GoType.
type new-doctype-2 struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	 string `json:"" db:""`
	 string `json:"" db:""`
}
