// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Portal Settings is the type-safe Go struct generated from the Portal Settings GoType.
type Portal Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DefaultRole string `json:"default_role" db:"default_role"`
	StandardMenuItems string `json:"standard_menu_items" db:"standard_menu_items"`
	HideStandardMenu int `json:"hide_standard_menu" db:"hide_standard_menu"`
	Menu string `json:"menu" db:"menu"`
	CustomSidebarMenu string `json:"custom_sidebar_menu" db:"custom_sidebar_menu"`
	CustomMenu string `json:"custom_menu" db:"custom_menu"`
	DefaultPortalHome string `json:"default_portal_home" db:"default_portal_home"`
}
