// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Package Import is the type-safe Go struct generated from the Package Import GoType.
type Package Import struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	AttachPackage string `json:"attach_package" db:"attach_package"`
	Activate int `json:"activate" db:"activate"`
	Log string `json:"log" db:"log"`
	Force int `json:"force" db:"force"`
}
