// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DocType Layout is the type-safe Go struct generated from the DocType Layout GoType.
type DocType Layout struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
	Fields string `json:"fields" db:"fields"`
	ClientScript string `json:"client_script" db:"client_script"`
	Route string `json:"route" db:"route"`
}
