// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Discussion Topic is the type-safe Go struct generated from the Discussion Topic GoType.
type Discussion Topic struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceDocname string `json:"reference_docname" db:"reference_docname"`
}
