// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Document Naming Settings is the type-safe Go struct generated from the Document Naming Settings GoType.
type Document Naming Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SetupSeries string `json:"setup_series" db:"setup_series"`
	HelpHtml string `json:"help_html" db:"help_html"`
	UserMustAlwaysSelect int `json:"user_must_always_select" db:"user_must_always_select"`
	Update string `json:"update" db:"update"`
	UpdateSeries string `json:"update_series" db:"update_series"`
	Prefix string `json:"prefix" db:"prefix"`
	CurrentValue int `json:"current_value" db:"current_value"`
	UpdateSeriesStart string `json:"update_series_start" db:"update_series_start"`
	NamingSeriesOptions string `json:"naming_series_options" db:"naming_series_options"`
	TryNamingSeries string `json:"try_naming_series" db:"try_naming_series"`
	TransactionType string `json:"transaction_type" db:"transaction_type"`
	ColumnBreak9 string `json:"column_break_9" db:"column_break_9"`
	NamingSeriesTab string `json:"naming_series_tab" db:"naming_series_tab"`
	SeriesPreview string `json:"series_preview" db:"series_preview"`
	AmendedDocumentsSection string `json:"amended_documents_section" db:"amended_documents_section"`
	DefaultAmendNaming string `json:"default_amend_naming" db:"default_amend_naming"`
	AmendNamingOverride string `json:"amend_naming_override" db:"amend_naming_override"`
	UpdateAmendmentNaming string `json:"update_amendment_naming" db:"update_amendment_naming"`
}
