// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Error Log is the type-safe Go struct generated from the Error Log GoType.
type Error Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
}
