// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Page is the type-safe Go struct generated from the Page GoType.
type Page struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SystemPage int `json:"system_page" db:"system_page"`
	PageHtml string `json:"page_html" db:"page_html"`
	PageName string `json:"page_name" db:"page_name"`
	Title string `json:"title" db:"title"`
	Icon string `json:"icon" db:"icon"`
	ColumnBreak0 string `json:"column_break0" db:"column_break0"`
	Module string `json:"module" db:"module"`
	RestrictToDomain string `json:"restrict_to_domain" db:"restrict_to_domain"`
	Standard string `json:"standard" db:"standard"`
	SectionBreak0 string `json:"section_break0" db:"section_break0"`
	Roles string `json:"roles" db:"roles"`
}
