// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Print Format is the type-safe Go struct generated from the Print Format GoType.
type Print Format struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocType string `json:"doc_type" db:"doc_type"`
	Module string `json:"module" db:"module"`
	Disabled int `json:"disabled" db:"disabled"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	Standard string `json:"standard" db:"standard"`
	CustomFormat int `json:"custom_format" db:"custom_format"`
	SectionBreak6 string `json:"section_break_6" db:"section_break_6"`
	PrintFormatType string `json:"print_format_type" db:"print_format_type"`
	RawPrinting int `json:"raw_printing" db:"raw_printing"`
	Html string `json:"html" db:"html"`
	RawCommands string `json:"raw_commands" db:"raw_commands"`
	SectionBreak9 string `json:"section_break_9" db:"section_break_9"`
	AlignLabelsRight int `json:"align_labels_right" db:"align_labels_right"`
	ShowSectionHeadings int `json:"show_section_headings" db:"show_section_headings"`
	LineBreaks int `json:"line_breaks" db:"line_breaks"`
	ColumnBreak11 string `json:"column_break_11" db:"column_break_11"`
	DefaultPrintLanguage string `json:"default_print_language" db:"default_print_language"`
	Font string `json:"font" db:"font"`
	CssSection string `json:"css_section" db:"css_section"`
	Css string `json:"css" db:"css"`
	CustomHtmlHelp string `json:"custom_html_help" db:"custom_html_help"`
	SectionBreak13 string `json:"section_break_13" db:"section_break_13"`
	PrintFormatHelp string `json:"print_format_help" db:"print_format_help"`
	FormatData string `json:"format_data" db:"format_data"`
	PrintFormatBuilder int `json:"print_format_builder" db:"print_format_builder"`
	AbsoluteValue int `json:"absolute_value" db:"absolute_value"`
	PrintFormatBuilderBeta int `json:"print_format_builder_beta" db:"print_format_builder_beta"`
	MarginTop float64 `json:"margin_top" db:"margin_top"`
	MarginBottom float64 `json:"margin_bottom" db:"margin_bottom"`
	MarginLeft float64 `json:"margin_left" db:"margin_left"`
	MarginRight float64 `json:"margin_right" db:"margin_right"`
	FontSize int `json:"font_size" db:"font_size"`
	PageNumber string `json:"page_number" db:"page_number"`
	PdfGenerator string `json:"pdf_generator" db:"pdf_generator"`
	PrintFormatFor string `json:"print_format_for" db:"print_format_for"`
	Report string `json:"report" db:"report"`
}
