// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// User Session Display is the type-safe Go struct generated from the User Session Display GoType.
type User Session Display struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Id string `json:"id" db:"id"`
	IpAddress string `json:"ip_address" db:"ip_address"`
	SessionCreated string `json:"session_created" db:"session_created"`
	LastUpdated string `json:"last_updated" db:"last_updated"`
	SignOut string `json:"sign_out" db:"sign_out"`
	ColumnBreakCjgl string `json:"column_break_cjgl" db:"column_break_cjgl"`
	ActionsSection string `json:"actions_section" db:"actions_section"`
	UserAgent string `json:"user_agent" db:"user_agent"`
	IsCurrent int `json:"is_current" db:"is_current"`
}
