// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Web Form Request is the type-safe Go struct generated from the Web Form Request GoType.
type Web Form Request struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	WebForm string `json:"web_form" db:"web_form"`
	ColumnBreakZjyx string `json:"column_break_zjyx" db:"column_break_zjyx"`
	Key string `json:"key" db:"key"`
	ExpiresOn string `json:"expires_on" db:"expires_on"`
	SectionBreakMuzz string `json:"section_break_muzz" db:"section_break_muzz"`
	WebFormValues string `json:"web_form_values" db:"web_form_values"`
	SectionBreakWlsa string `json:"section_break_wlsa" db:"section_break_wlsa"`
	DocValues string `json:"doc_values" db:"doc_values"`
	SectionBreakVjqn string `json:"section_break_vjqn" db:"section_break_vjqn"`
	References string `json:"references" db:"references"`
	FirstUsedOn string `json:"first_used_on" db:"first_used_on"`
}
