// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Note is the type-safe Go struct generated from the Note GoType.
type Note struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	Public int `json:"public" db:"public"`
	NotifyOnLogin int `json:"notify_on_login" db:"notify_on_login"`
	NotifyOnEveryLogin int `json:"notify_on_every_login" db:"notify_on_every_login"`
	ExpireNotificationOn string `json:"expire_notification_on" db:"expire_notification_on"`
	Content string `json:"content" db:"content"`
	SeenBySection string `json:"seen_by_section" db:"seen_by_section"`
	SeenBy string `json:"seen_by" db:"seen_by"`
}
