// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Has Domain is the type-safe Go struct generated from the Has Domain GoType.
type Has Domain struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Domain string `json:"domain" db:"domain"`
}
