// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Google Calendar is the type-safe Go struct generated from the Google Calendar GoType.
type Google Calendar struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Enable int `json:"enable" db:"enable"`
	Sb00 string `json:"sb_00" db:"sb_00"`
	User string `json:"user" db:"user"`
	CalendarName string `json:"calendar_name" db:"calendar_name"`
	SectionBreak3 string `json:"section_break_3" db:"section_break_3"`
	RefreshToken string `json:"refresh_token" db:"refresh_token"`
	AuthorizationCode string `json:"authorization_code" db:"authorization_code"`
	NextSyncToken string `json:"next_sync_token" db:"next_sync_token"`
	GoogleCalendarId string `json:"google_calendar_id" db:"google_calendar_id"`
	AuthorizeGoogleCalendarAccess string `json:"authorize_google_calendar_access" db:"authorize_google_calendar_access"`
	Sb01 string `json:"sb_01" db:"sb_01"`
	PullFromGoogleCalendar int `json:"pull_from_google_calendar" db:"pull_from_google_calendar"`
	SyncAsPublic int `json:"sync_as_public" db:"sync_as_public"`
	Cb01 string `json:"cb_01" db:"cb_01"`
	PushToGoogleCalendar int `json:"push_to_google_calendar" db:"push_to_google_calendar"`
}
