// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Notification Type Preference is the type-safe Go struct generated from the Notification Type Preference GoType.
type Notification Type Preference struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	NotificationType string `json:"notification_type" db:"notification_type"`
}
