// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// User Doctype Permissions is the type-safe Go struct generated from the User Doctype Permissions GoType.
type User Doctype Permissions struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
}
