// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Google Contacts is the type-safe Go struct generated from the Google Contacts GoType.
type Google Contacts struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Enable int `json:"enable" db:"enable"`
	AuthorizationCode string `json:"authorization_code" db:"authorization_code"`
	RefreshToken string `json:"refresh_token" db:"refresh_token"`
	LastSyncOn string `json:"last_sync_on" db:"last_sync_on"`
	EmailId string `json:"email_id" db:"email_id"`
	Sb00 string `json:"sb_00" db:"sb_00"`
	Cb00 string `json:"cb_00" db:"cb_00"`
	AuthorizeGoogleContactsAccess string `json:"authorize_google_contacts_access" db:"authorize_google_contacts_access"`
	NextSyncToken string `json:"next_sync_token" db:"next_sync_token"`
	Sync string `json:"sync" db:"sync"`
	PullFromGoogleContacts int `json:"pull_from_google_contacts" db:"pull_from_google_contacts"`
	ColumnBreak12 string `json:"column_break_12" db:"column_break_12"`
	PushToGoogleContacts int `json:"push_to_google_contacts" db:"push_to_google_contacts"`
}
