// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Auto Repeat is the type-safe Go struct generated from the Auto Repeat GoType.
type Auto Repeat struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceDocument string `json:"reference_document" db:"reference_document"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	StartDate string `json:"start_date" db:"start_date"`
	EndDate string `json:"end_date" db:"end_date"`
	Disabled int `json:"disabled" db:"disabled"`
	SectionBreak10 string `json:"section_break_10" db:"section_break_10"`
	Frequency string `json:"frequency" db:"frequency"`
	ColumnBreak12 string `json:"column_break_12" db:"column_break_12"`
	RepeatOnDay int `json:"repeat_on_day" db:"repeat_on_day"`
	NextScheduleDate string `json:"next_schedule_date" db:"next_schedule_date"`
	Notification string `json:"notification" db:"notification"`
	NotifyByEmail int `json:"notify_by_email" db:"notify_by_email"`
	Recipients string `json:"recipients" db:"recipients"`
	GetContacts string `json:"get_contacts" db:"get_contacts"`
	Template string `json:"template" db:"template"`
	Subject string `json:"subject" db:"subject"`
	Message string `json:"message" db:"message"`
	PreviewMessage string `json:"preview_message" db:"preview_message"`
	PrintFormat string `json:"print_format" db:"print_format"`
	Status string `json:"status" db:"status"`
	RepeatOnLastDay int `json:"repeat_on_last_day" db:"repeat_on_last_day"`
	RepeatOnDays string `json:"repeat_on_days" db:"repeat_on_days"`
	SubmitOnCreation int `json:"submit_on_creation" db:"submit_on_creation"`
	SectionBreak16 string `json:"section_break_16" db:"section_break_16"`
	GenerateSeparateDocumentsForEachAssignee int `json:"generate_separate_documents_for_each_assignee" db:"generate_separate_documents_for_each_assignee"`
	SectionBreakLooa string `json:"section_break_looa" db:"section_break_looa"`
	Assignee string `json:"assignee" db:"assignee"`
}
