// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// OAuth Provider Settings is the type-safe Go struct generated from the OAuth Provider Settings GoType.
type OAuth Provider Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SkipAuthorization string `json:"skip_authorization" db:"skip_authorization"`
}
