// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workflow Transition Task is the type-safe Go struct generated from the Workflow Transition Task GoType.
type Workflow Transition Task struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Task string `json:"task" db:"task"`
	Enabled int `json:"enabled" db:"enabled"`
	Link string `json:"link" db:"link"`
	Asynchronous int `json:"asynchronous" db:"asynchronous"`
}
