// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Property Setter is the type-safe Go struct generated from the Property Setter GoType.
type Property Setter struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Help string `json:"help" db:"help"`
	Sb0 string `json:"sb0" db:"sb0"`
	DoctypeOrField string `json:"doctype_or_field" db:"doctype_or_field"`
	Value string `json:"value" db:"value"`
	ColumnBreak0 string `json:"column_break0" db:"column_break0"`
	DocType string `json:"doc_type" db:"doc_type"`
	FieldName string `json:"field_name" db:"field_name"`
	Property string `json:"property" db:"property"`
	PropertyType string `json:"property_type" db:"property_type"`
	DefaultValue string `json:"default_value" db:"default_value"`
	RowName string `json:"row_name" db:"row_name"`
	Module string `json:"module" db:"module"`
	SectionBreak9 string `json:"section_break_9" db:"section_break_9"`
	IsSystemGenerated int `json:"is_system_generated" db:"is_system_generated"`
}
