// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Contact Phone is the type-safe Go struct generated from the Contact Phone GoType.
type Contact Phone struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Phone string `json:"phone" db:"phone"`
	IsPrimaryPhone int `json:"is_primary_phone" db:"is_primary_phone"`
	IsPrimaryMobileNo int `json:"is_primary_mobile_no" db:"is_primary_mobile_no"`
}
