// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workflow Action is the type-safe Go struct generated from the Workflow Action GoType.
type Workflow Action struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Status string `json:"status" db:"status"`
	ReferenceName string `json:"reference_name" db:"reference_name"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	User string `json:"user" db:"user"`
	WorkflowState string `json:"workflow_state" db:"workflow_state"`
	CompletedBy string `json:"completed_by" db:"completed_by"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	CompletedByRole string `json:"completed_by_role" db:"completed_by_role"`
	PermittedRoles string `json:"permitted_roles" db:"permitted_roles"`
}
