// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workspace Chart is the type-safe Go struct generated from the Workspace Chart GoType.
type Workspace Chart struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ChartName string `json:"chart_name" db:"chart_name"`
	Label string `json:"label" db:"label"`
}
