// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Number Card is the type-safe Go struct generated from the Number Card GoType.
type Number Card struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
	Function string `json:"function" db:"function"`
	AggregateFunctionBasedOn string `json:"aggregate_function_based_on" db:"aggregate_function_based_on"`
	FiltersJson string `json:"filters_json" db:"filters_json"`
	Label string `json:"label" db:"label"`
	Color string `json:"color" db:"color"`
	ColumnBreak2 string `json:"column_break_2" db:"column_break_2"`
	FiltersSection string `json:"filters_section" db:"filters_section"`
	IsPublic int `json:"is_public" db:"is_public"`
	ShowPercentageStats int `json:"show_percentage_stats" db:"show_percentage_stats"`
	StatsTimeInterval string `json:"stats_time_interval" db:"stats_time_interval"`
	StatsSection string `json:"stats_section" db:"stats_section"`
	IsStandard int `json:"is_standard" db:"is_standard"`
	Module string `json:"module" db:"module"`
	DynamicFiltersJson string `json:"dynamic_filters_json" db:"dynamic_filters_json"`
	SectionBreak16 string `json:"section_break_16" db:"section_break_16"`
	DynamicFiltersSection string `json:"dynamic_filters_section" db:"dynamic_filters_section"`
	Type string `json:"type" db:"type"`
	ReportName string `json:"report_name" db:"report_name"`
	ReportField string `json:"report_field" db:"report_field"`
	Method string `json:"method" db:"method"`
	CustomConfigurationSection string `json:"custom_configuration_section" db:"custom_configuration_section"`
	FiltersConfig string `json:"filters_config" db:"filters_config"`
	ReportFunction string `json:"report_function" db:"report_function"`
	ParentDocumentType string `json:"parent_document_type" db:"parent_document_type"`
	Currency string `json:"currency" db:"currency"`
	ColumnBreakXtre string `json:"column_break_xtre" db:"column_break_xtre"`
	BackgroundColor string `json:"background_color" db:"background_color"`
	ShowFullNumber int `json:"show_full_number" db:"show_full_number"`
}
