// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Dashboard Chart is the type-safe Go struct generated from the Dashboard Chart GoType.
type Dashboard Chart struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ChartName string `json:"chart_name" db:"chart_name"`
	ChartType string `json:"chart_type" db:"chart_type"`
	Source string `json:"source" db:"source"`
	DocumentType string `json:"document_type" db:"document_type"`
	BasedOn string `json:"based_on" db:"based_on"`
	ValueBasedOn string `json:"value_based_on" db:"value_based_on"`
	ColumnBreak6 string `json:"column_break_6" db:"column_break_6"`
	Timespan string `json:"timespan" db:"timespan"`
	TimeInterval string `json:"time_interval" db:"time_interval"`
	Timeseries int `json:"timeseries" db:"timeseries"`
	FiltersSection string `json:"filters_section" db:"filters_section"`
	FiltersJson string `json:"filters_json" db:"filters_json"`
	ChartOptionsSection string `json:"chart_options_section" db:"chart_options_section"`
	Type string `json:"type" db:"type"`
	ColumnBreak2 string `json:"column_break_2" db:"column_break_2"`
	Color string `json:"color" db:"color"`
	SectionBreak10 string `json:"section_break_10" db:"section_break_10"`
	LastSyncedOn string `json:"last_synced_on" db:"last_synced_on"`
	GroupByBasedOn string `json:"group_by_based_on" db:"group_by_based_on"`
	GroupByType string `json:"group_by_type" db:"group_by_type"`
	AggregateFunctionBasedOn string `json:"aggregate_function_based_on" db:"aggregate_function_based_on"`
	NumberOfGroups int `json:"number_of_groups" db:"number_of_groups"`
	FromDate string `json:"from_date" db:"from_date"`
	ToDate string `json:"to_date" db:"to_date"`
	XField string `json:"x_field" db:"x_field"`
	ReportName string `json:"report_name" db:"report_name"`
	YAxis string `json:"y_axis" db:"y_axis"`
	CustomOptions string `json:"custom_options" db:"custom_options"`
	IsPublic int `json:"is_public" db:"is_public"`
	HeatmapYear string `json:"heatmap_year" db:"heatmap_year"`
	IsStandard int `json:"is_standard" db:"is_standard"`
	Module string `json:"module" db:"module"`
	DynamicFiltersJson string `json:"dynamic_filters_json" db:"dynamic_filters_json"`
	DynamicFiltersSection string `json:"dynamic_filters_section" db:"dynamic_filters_section"`
	UseReportChart int `json:"use_report_chart" db:"use_report_chart"`
	ParentDocumentType string `json:"parent_document_type" db:"parent_document_type"`
	Roles string `json:"roles" db:"roles"`
	Currency string `json:"currency" db:"currency"`
	ShowValuesOverChart int `json:"show_values_over_chart" db:"show_values_over_chart"`
}
