// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workspace Sidebar is the type-safe Go struct generated from the Workspace Sidebar GoType.
type Workspace Sidebar struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	Items string `json:"items" db:"items"`
	HeaderIcon string `json:"header_icon" db:"header_icon"`
	App string `json:"app" db:"app"`
	ForUser string `json:"for_user" db:"for_user"`
	Module string `json:"module" db:"module"`
	Standard int `json:"standard" db:"standard"`
	ColumnBreakPukb string `json:"column_break_pukb" db:"column_break_pukb"`
	SectionBreakVdyo string `json:"section_break_vdyo" db:"section_break_vdyo"`
	ModuleOnboarding string `json:"module_onboarding" db:"module_onboarding"`
}
