// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Email Domain is the type-safe Go struct generated from the Email Domain GoType.
type Email Domain struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	EmailSettings string `json:"email_settings" db:"email_settings"`
	DomainName string `json:"domain_name" db:"domain_name"`
	MailboxSettings string `json:"mailbox_settings" db:"mailbox_settings"`
	EmailServer string `json:"email_server" db:"email_server"`
	UseImap int `json:"use_imap" db:"use_imap"`
	UseSsl int `json:"use_ssl" db:"use_ssl"`
	UseStarttls int `json:"use_starttls" db:"use_starttls"`
	AttachmentLimit int `json:"attachment_limit" db:"attachment_limit"`
	OutgoingMailSettings string `json:"outgoing_mail_settings" db:"outgoing_mail_settings"`
	SmtpServer string `json:"smtp_server" db:"smtp_server"`
	UseTls int `json:"use_tls" db:"use_tls"`
	SmtpPort string `json:"smtp_port" db:"smtp_port"`
	IncomingPort string `json:"incoming_port" db:"incoming_port"`
	AppendEmailsToSentFolder int `json:"append_emails_to_sent_folder" db:"append_emails_to_sent_folder"`
	UseSslForOutgoing int `json:"use_ssl_for_outgoing" db:"use_ssl_for_outgoing"`
	ColumnBreak9 string `json:"column_break_9" db:"column_break_9"`
	ColumnBreak18 string `json:"column_break_18" db:"column_break_18"`
	ValidateSslCertificate int `json:"validate_ssl_certificate" db:"validate_ssl_certificate"`
	ValidateSslCertificateForOutgoing int `json:"validate_ssl_certificate_for_outgoing" db:"validate_ssl_certificate_for_outgoing"`
	SentFolderName string `json:"sent_folder_name" db:"sent_folder_name"`
}
