// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Data Import Log is the type-safe Go struct generated from the Data Import Log GoType.
type Data Import Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DataImport string `json:"data_import" db:"data_import"`
	Docname string `json:"docname" db:"docname"`
	Exception string `json:"exception" db:"exception"`
	RowIndexes string `json:"row_indexes" db:"row_indexes"`
	Success int `json:"success" db:"success"`
	LogIndex int `json:"log_index" db:"log_index"`
	Messages string `json:"messages" db:"messages"`
}
