// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// User Email is the type-safe Go struct generated from the User Email GoType.
type User Email struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	EmailAccount string `json:"email_account" db:"email_account"`
	EmailId string `json:"email_id" db:"email_id"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	AwaitingPassword int `json:"awaiting_password" db:"awaiting_password"`
	EnableOutgoing int `json:"enable_outgoing" db:"enable_outgoing"`
	UsedOauth int `json:"used_oauth" db:"used_oauth"`
}
