// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Custom HTML Block is the type-safe Go struct generated from the Custom HTML Block GoType.
type Custom HTML Block struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	HtmlSection string `json:"html_section" db:"html_section"`
	Html string `json:"html" db:"html"`
	PreviewSection string `json:"preview_section" db:"preview_section"`
	Preview string `json:"preview" db:"preview"`
	JavascriptSection string `json:"javascript_section" db:"javascript_section"`
	Script string `json:"script" db:"script"`
	CssSection string `json:"css_section" db:"css_section"`
	Style string `json:"style" db:"style"`
	JsMessage string `json:"js_message" db:"js_message"`
	RolesSection string `json:"roles_section" db:"roles_section"`
	Roles string `json:"roles" db:"roles"`
	Private int `json:"private" db:"private"`
}
