// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Log Setting User is the type-safe Go struct generated from the Log Setting User GoType.
type Log Setting User struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	User string `json:"user" db:"user"`
}
