// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workflow Transition is the type-safe Go struct generated from the Workflow Transition GoType.
type Workflow Transition struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	State string `json:"state" db:"state"`
	Action string `json:"action" db:"action"`
	NextState string `json:"next_state" db:"next_state"`
	Allowed string `json:"allowed" db:"allowed"`
	AllowSelfApproval int `json:"allow_self_approval" db:"allow_self_approval"`
	Conditions string `json:"conditions" db:"conditions"`
	Condition string `json:"condition" db:"condition"`
	ColumnBreak7 string `json:"column_break_7" db:"column_break_7"`
	Example string `json:"example" db:"example"`
	WorkflowBuilderId string `json:"workflow_builder_id" db:"workflow_builder_id"`
	SendEmailToCreator int `json:"send_email_to_creator" db:"send_email_to_creator"`
	TransitionTasks string `json:"transition_tasks" db:"transition_tasks"`
}
