// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Customize Form Field is the type-safe Go struct generated from the Customize Form Field GoType.
type Customize Form Field struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	LabelAndType string `json:"label_and_type" db:"label_and_type"`
	Label string `json:"label" db:"label"`
	Fieldtype string `json:"fieldtype" db:"fieldtype"`
	Fieldname string `json:"fieldname" db:"fieldname"`
	Reqd int `json:"reqd" db:"reqd"`
	Unique int `json:"unique" db:"unique"`
	IsVirtual int `json:"is_virtual" db:"is_virtual"`
	InListView int `json:"in_list_view" db:"in_list_view"`
	InStandardFilter int `json:"in_standard_filter" db:"in_standard_filter"`
	InGlobalSearch int `json:"in_global_search" db:"in_global_search"`
	Bold int `json:"bold" db:"bold"`
	Translatable int `json:"translatable" db:"translatable"`
	ColumnBreak7 string `json:"column_break_7" db:"column_break_7"`
	Precision string `json:"precision" db:"precision"`
	Length int `json:"length" db:"length"`
	Options string `json:"options" db:"options"`
	FetchFrom string `json:"fetch_from" db:"fetch_from"`
	FetchIfEmpty int `json:"fetch_if_empty" db:"fetch_if_empty"`
	Permissions string `json:"permissions" db:"permissions"`
	DependsOn string `json:"depends_on" db:"depends_on"`
	Permlevel int `json:"permlevel" db:"permlevel"`
	Hidden int `json:"hidden" db:"hidden"`
	ReadOnly int `json:"read_only" db:"read_only"`
	Collapsible int `json:"collapsible" db:"collapsible"`
	AllowBulkEdit int `json:"allow_bulk_edit" db:"allow_bulk_edit"`
	CollapsibleDependsOn string `json:"collapsible_depends_on" db:"collapsible_depends_on"`
	ColumnBreak14 string `json:"column_break_14" db:"column_break_14"`
	IgnoreUserPermissions int `json:"ignore_user_permissions" db:"ignore_user_permissions"`
	AllowOnSubmit int `json:"allow_on_submit" db:"allow_on_submit"`
	ReportHide int `json:"report_hide" db:"report_hide"`
	RememberLastSelectedValue int `json:"remember_last_selected_value" db:"remember_last_selected_value"`
	Display string `json:"display" db:"display"`
	Default string `json:"default" db:"default"`
	InFilter int `json:"in_filter" db:"in_filter"`
	ColumnBreak21 string `json:"column_break_21" db:"column_break_21"`
	Description string `json:"description" db:"description"`
	PrintHide int `json:"print_hide" db:"print_hide"`
	PrintHideIfNoValue int `json:"print_hide_if_no_value" db:"print_hide_if_no_value"`
	PrintWidth string `json:"print_width" db:"print_width"`
	Alignment string `json:"alignment" db:"alignment"`
	Columns int `json:"columns" db:"columns"`
	Width string `json:"width" db:"width"`
	IsCustomField int `json:"is_custom_field" db:"is_custom_field"`
	AllowInQuickEntry int `json:"allow_in_quick_entry" db:"allow_in_quick_entry"`
	PropertyDependsOnSection string `json:"property_depends_on_section" db:"property_depends_on_section"`
	MandatoryDependsOn string `json:"mandatory_depends_on" db:"mandatory_depends_on"`
	ColumnBreak33 string `json:"column_break_33" db:"column_break_33"`
	ReadOnlyDependsOn string `json:"read_only_depends_on" db:"read_only_depends_on"`
	InPreview int `json:"in_preview" db:"in_preview"`
	HideSeconds int `json:"hide_seconds" db:"hide_seconds"`
	HideDays int `json:"hide_days" db:"hide_days"`
	HideBorder int `json:"hide_border" db:"hide_border"`
	NonNegative int `json:"non_negative" db:"non_negative"`
	ShowDashboard int `json:"show_dashboard" db:"show_dashboard"`
	NoCopy int `json:"no_copy" db:"no_copy"`
	IsSystemGenerated int `json:"is_system_generated" db:"is_system_generated"`
	IgnoreXssFilter int `json:"ignore_xss_filter" db:"ignore_xss_filter"`
	SortOptions int `json:"sort_options" db:"sort_options"`
	LinkFilters string `json:"link_filters" db:"link_filters"`
	Placeholder string `json:"placeholder" db:"placeholder"`
	ButtonColor string `json:"button_color" db:"button_color"`
	Mask int `json:"mask" db:"mask"`
	SetOnlyOnce int `json:"set_only_once" db:"set_only_once"`
}
