// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// User Social Login is the type-safe Go struct generated from the User Social Login GoType.
type User Social Login struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Provider string `json:"provider" db:"provider"`
	SectionBreak0 string `json:"section_break_0" db:"section_break_0"`
	Username string `json:"username" db:"username"`
	ColumnBreak0 string `json:"column_break_0" db:"column_break_0"`
	Userid string `json:"userid" db:"userid"`
}
