// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Print Format Field Template is the type-safe Go struct generated from the Print Format Field Template GoType.
type Print Format Field Template struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
	Field string `json:"field" db:"field"`
	Template string `json:"template" db:"template"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	SectionBreak5 string `json:"section_break_5" db:"section_break_5"`
	Module string `json:"module" db:"module"`
	Standard int `json:"standard" db:"standard"`
	TemplateFile string `json:"template_file" db:"template_file"`
}
