// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Scheduled Job Log is the type-safe Go struct generated from the Scheduled Job Log GoType.
type Scheduled Job Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Status string `json:"status" db:"status"`
	Details string `json:"details" db:"details"`
	ScheduledJobType string `json:"scheduled_job_type" db:"scheduled_job_type"`
	DebugLog string `json:"debug_log" db:"debug_log"`
}
