// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// About Us Team Member is the type-safe Go struct generated from the About Us Team Member GoType.
type About Us Team Member struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	FullName string `json:"full_name" db:"full_name"`
	ImageLink string `json:"image_link" db:"image_link"`
	Bio string `json:"bio" db:"bio"`
}
