// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Tag is the type-safe Go struct generated from the Tag GoType.
type Tag struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Description string `json:"description" db:"description"`
}
