// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Role is the type-safe Go struct generated from the Role GoType.
type Role struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	RoleName string `json:"role_name" db:"role_name"`
	Disabled int `json:"disabled" db:"disabled"`
	DeskAccess int `json:"desk_access" db:"desk_access"`
	IsCustom int `json:"is_custom" db:"is_custom"`
}
