// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Note Seen By is the type-safe Go struct generated from the Note Seen By GoType.
type Note Seen By struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	User string `json:"user" db:"user"`
}
