// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Email Flag Queue is the type-safe Go struct generated from the Email Flag Queue GoType.
type Email Flag Queue struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	IsCompleted int `json:"is_completed" db:"is_completed"`
	Communication string `json:"communication" db:"communication"`
	Action string `json:"action" db:"action"`
	EmailAccount string `json:"email_account" db:"email_account"`
	Uid string `json:"uid" db:"uid"`
}
