// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Changelog Feed is the type-safe Go struct generated from the Changelog Feed GoType.
type Changelog Feed struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	AppName string `json:"app_name" db:"app_name"`
	Link string `json:"link" db:"link"`
	PostingTimestamp string `json:"posting_timestamp" db:"posting_timestamp"`
}
