// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// User Select Document Type is the type-safe Go struct generated from the User Select Document Type GoType.
type User Select Document Type struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
}
