// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DocType Action is the type-safe Go struct generated from the DocType Action GoType.
type DocType Action struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Label string `json:"label" db:"label"`
	Group string `json:"group" db:"group"`
	ActionType string `json:"action_type" db:"action_type"`
	Action string `json:"action" db:"action"`
	Hidden int `json:"hidden" db:"hidden"`
	Custom int `json:"custom" db:"custom"`
}
