// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Form Tour is the type-safe Go struct generated from the Form Tour GoType.
type Form Tour struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	Steps string `json:"steps" db:"steps"`
	SectionBreak3 string `json:"section_break_3" db:"section_break_3"`
	Title string `json:"title" db:"title"`
	SaveOnComplete int `json:"save_on_complete" db:"save_on_complete"`
	IsStandard int `json:"is_standard" db:"is_standard"`
	Module string `json:"module" db:"module"`
	ColumnBreak6 string `json:"column_break_6" db:"column_break_6"`
	FirstDocument int `json:"first_document" db:"first_document"`
	IncludeNameField int `json:"include_name_field" db:"include_name_field"`
	UiTour int `json:"ui_tour" db:"ui_tour"`
	PageRoute string `json:"page_route" db:"page_route"`
	DashboardName string `json:"dashboard_name" db:"dashboard_name"`
	ViewName string `json:"view_name" db:"view_name"`
	WorkspaceName string `json:"workspace_name" db:"workspace_name"`
	PageName string `json:"page_name" db:"page_name"`
	ListName string `json:"list_name" db:"list_name"`
	ReportName string `json:"report_name" db:"report_name"`
	TrackSteps int `json:"track_steps" db:"track_steps"`
	NewDocumentForm int `json:"new_document_form" db:"new_document_form"`
}
