// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Tag Link is the type-safe Go struct generated from the Tag Link GoType.
type Tag Link struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	Tag string `json:"tag" db:"tag"`
	DocumentType string `json:"document_type" db:"document_type"`
	DocumentName string `json:"document_name" db:"document_name"`
}
