// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Kanban Board is the type-safe Go struct generated from the Kanban Board GoType.
type Kanban Board struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	KanbanBoardName string `json:"kanban_board_name" db:"kanban_board_name"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	FieldName string `json:"field_name" db:"field_name"`
	SectionBreak3 string `json:"section_break_3" db:"section_break_3"`
	Columns string `json:"columns" db:"columns"`
	Filters string `json:"filters" db:"filters"`
	Private int `json:"private" db:"private"`
	Fields string `json:"fields" db:"fields"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	ShowLabels int `json:"show_labels" db:"show_labels"`
}
