// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Reminder is the type-safe Go struct generated from the Reminder GoType.
type Reminder struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	User string `json:"user" db:"user"`
	ReminderDoctype string `json:"reminder_doctype" db:"reminder_doctype"`
	ReminderDocname string `json:"reminder_docname" db:"reminder_docname"`
	RemindAt string `json:"remind_at" db:"remind_at"`
	Description string `json:"description" db:"description"`
	Notified int `json:"notified" db:"notified"`
}
