// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Social Login Key is the type-safe Go struct generated from the Social Login Key GoType.
type Social Login Key struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	EnableSocialLogin int `json:"enable_social_login" db:"enable_social_login"`
	ClientCredentials string `json:"client_credentials" db:"client_credentials"`
	SocialLoginProvider string `json:"social_login_provider" db:"social_login_provider"`
	ClientId string `json:"client_id" db:"client_id"`
	ColumnBreak0 string `json:"column_break_0" db:"column_break_0"`
	ProviderName string `json:"provider_name" db:"provider_name"`
	ClientSecret string `json:"client_secret" db:"client_secret"`
	SbIdentityDetails string `json:"sb_identity_details" db:"sb_identity_details"`
	Icon string `json:"icon" db:"icon"`
	ColumnBreak1 string `json:"column_break_1" db:"column_break_1"`
	BaseUrl string `json:"base_url" db:"base_url"`
	ClientUrls string `json:"client_urls" db:"client_urls"`
	AuthorizeUrl string `json:"authorize_url" db:"authorize_url"`
	AccessTokenUrl string `json:"access_token_url" db:"access_token_url"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	RedirectUrl string `json:"redirect_url" db:"redirect_url"`
	ApiEndpoint string `json:"api_endpoint" db:"api_endpoint"`
	CustomBaseUrl int `json:"custom_base_url" db:"custom_base_url"`
	ClientInformation string `json:"client_information" db:"client_information"`
	ApiEndpointArgs string `json:"api_endpoint_args" db:"api_endpoint_args"`
	AuthUrlData string `json:"auth_url_data" db:"auth_url_data"`
	UserIdProperty string `json:"user_id_property" db:"user_id_property"`
	ConfigurationSection string `json:"configuration_section" db:"configuration_section"`
	SignUps string `json:"sign_ups" db:"sign_ups"`
	ShowInResourceMetadata int `json:"show_in_resource_metadata" db:"show_in_resource_metadata"`
}
