// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Permission Log is the type-safe Go struct generated from the Permission Log GoType.
type Permission Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ChangedBy string `json:"changed_by" db:"changed_by"`
	ChangedAt string `json:"changed_at" db:"changed_at"`
	Changes string `json:"changes" db:"changes"`
	ChangedValues string `json:"changed_values" db:"changed_values"`
	ColumnBreakGvuy string `json:"column_break_gvuy" db:"column_break_gvuy"`
	SectionBreakTtv7 string `json:"section_break_ttv7" db:"section_break_ttv7"`
	ColumnBreakAcow string `json:"column_break_acow" db:"column_break_acow"`
	SectionBreakMt9x string `json:"section_break_mt9x" db:"section_break_mt9x"`
	SectionBreak6gd5 string `json:"section_break_6gd5" db:"section_break_6gd5"`
	ColumnBreak8nk0 string `json:"column_break_8nk0" db:"column_break_8nk0"`
	ForDoctype string `json:"for_doctype" db:"for_doctype"`
	ForDocument string `json:"for_document" db:"for_document"`
	ReferenceType string `json:"reference_type" db:"reference_type"`
	Reference string `json:"reference" db:"reference"`
	Status string `json:"status" db:"status"`
}
