// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workflow is the type-safe Go struct generated from the Workflow GoType.
type Workflow struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	WorkflowName string `json:"workflow_name" db:"workflow_name"`
	DocumentType string `json:"document_type" db:"document_type"`
	IsActive int `json:"is_active" db:"is_active"`
	OverrideStatus int `json:"override_status" db:"override_status"`
	SendEmailAlert int `json:"send_email_alert" db:"send_email_alert"`
	EnableActionConfirmation int `json:"enable_action_confirmation" db:"enable_action_confirmation"`
	StatesHead string `json:"states_head" db:"states_head"`
	States string `json:"states" db:"states"`
	TransitionRules string `json:"transition_rules" db:"transition_rules"`
	Transitions string `json:"transitions" db:"transitions"`
	WorkflowStateField string `json:"workflow_state_field" db:"workflow_state_field"`
	WorkflowData string `json:"workflow_data" db:"workflow_data"`
}
