// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// System Health Report is the type-safe Go struct generated from the System Health Report GoType.
type System Health Report struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	BackgroundWorkers string `json:"background_workers" db:"background_workers"`
	TotalBackgroundWorkers int `json:"total_background_workers" db:"total_background_workers"`
	BackgroundJobsSection string `json:"background_jobs_section" db:"background_jobs_section"`
	SchedulerStatus string `json:"scheduler_status" db:"scheduler_status"`
	QueueStatus string `json:"queue_status" db:"queue_status"`
	ColumnBreakKlex string `json:"column_break_klex" db:"column_break_klex"`
	SectionBreakDjoz string `json:"section_break_djoz" db:"section_break_djoz"`
	ColumnBreakWjoz string `json:"column_break_wjoz" db:"column_break_wjoz"`
	BackgroundJobsTab string `json:"background_jobs_tab" db:"background_jobs_tab"`
	SocketioPingCheck string `json:"socketio_ping_check" db:"socketio_ping_check"`
	ColumnBreakHgay string `json:"column_break_hgay" db:"column_break_hgay"`
	SocketioTransportMode string `json:"socketio_transport_mode" db:"socketio_transport_mode"`
	OutgoingEmailsColumn string `json:"outgoing_emails_column" db:"outgoing_emails_column"`
	FailedEmails int `json:"failed_emails" db:"failed_emails"`
	TotalOutgoingEmails int `json:"total_outgoing_emails" db:"total_outgoing_emails"`
	PendingEmails int `json:"pending_emails" db:"pending_emails"`
	IncomingEmailsLast7DaysColumn string `json:"incoming_emails_last_7_days_column" db:"incoming_emails_last_7_days_column"`
	UnhandledEmails int `json:"unhandled_emails" db:"unhandled_emails"`
	HandledEmails int `json:"handled_emails" db:"handled_emails"`
	ErrorsGeneratedInLast1DaySection string `json:"errors_generated_in_last_1_day_section" db:"errors_generated_in_last_1_day_section"`
	TotalErrors int `json:"total_errors" db:"total_errors"`
	TopErrors string `json:"top_errors" db:"top_errors"`
	Database string `json:"database" db:"database"`
	DbStorageUsage float64 `json:"db_storage_usage" db:"db_storage_usage"`
	ColumnBreakAuhv string `json:"column_break_auhv" db:"column_break_auhv"`
	TopDbTables string `json:"top_db_tables" db:"top_db_tables"`
	DatabaseVersion string `json:"database_version" db:"database_version"`
	MariadbVariablesSection string `json:"mariadb_variables_section" db:"mariadb_variables_section"`
	BufferpoolSize string `json:"bufferpool_size" db:"bufferpool_size"`
	BinaryLogging string `json:"binary_logging" db:"binary_logging"`
	CacheKeys int `json:"cache_keys" db:"cache_keys"`
	CacheMemoryUsage string `json:"cache_memory_usage" db:"cache_memory_usage"`
	BackupsSize float64 `json:"backups_size" db:"backups_size"`
	PrivateFilesSize float64 `json:"private_files_size" db:"private_files_size"`
	PublicFilesSize float64 `json:"public_files_size" db:"public_files_size"`
	StorageUsageColumn string `json:"storage_usage_column" db:"storage_usage_column"`
	BackupsColumn string `json:"backups_column" db:"backups_column"`
	OnsiteBackups int `json:"onsite_backups" db:"onsite_backups"`
	TotalUsers int `json:"total_users" db:"total_users"`
	ColumnBreakYfwd string `json:"column_break_yfwd" db:"column_break_yfwd"`
	NewUsers int `json:"new_users" db:"new_users"`
	FailedLogins int `json:"failed_logins" db:"failed_logins"`
	ActiveSessions int `json:"active_sessions" db:"active_sessions"`
	Last10ActiveUsers string `json:"last_10_active_users" db:"last_10_active_users"`
	SectionBreakUdjs string `json:"section_break_udjs" db:"section_break_udjs"`
	DatabaseSection string `json:"database_section" db:"database_section"`
	CacheSection string `json:"cache_section" db:"cache_section"`
	ColumnBreakCcov string `json:"column_break_ccov" db:"column_break_ccov"`
	SectionBreakRyki string `json:"section_break_ryki" db:"section_break_ryki"`
	ColumnBreakVztw string `json:"column_break_vztw" db:"column_break_vztw"`
	ColumnBreakJnkt string `json:"column_break_jnkt" db:"column_break_jnkt"`
	BackupsSection string `json:"backups_section" db:"backups_section"`
	ColumnBreakLuox string `json:"column_break_luox" db:"column_break_luox"`
	UsersSection string `json:"users_section" db:"users_section"`
	RealtimeSocketioSection string `json:"realtime_socketio_section" db:"realtime_socketio_section"`
	BackgroundJobsCheck string `json:"background_jobs_check" db:"background_jobs_check"`
	TestJobId string `json:"test_job_id" db:"test_job_id"`
	ColumnBreakFzke string `json:"column_break_fzke" db:"column_break_fzke"`
	SchedulerSection string `json:"scheduler_section" db:"scheduler_section"`
	FailingScheduledJobs string `json:"failing_scheduled_jobs" db:"failing_scheduled_jobs"`
	ColumnBreakBxog string `json:"column_break_bxog" db:"column_break_bxog"`
	OldestUnscheduledJob string `json:"oldest_unscheduled_job" db:"oldest_unscheduled_job"`
	SectionBreakVpuw string `json:"section_break_vpuw" db:"section_break_vpuw"`
}
