// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DefaultValue is the type-safe Go struct generated from the DefaultValue GoType.
type DefaultValue struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Defkey string `json:"defkey" db:"defkey"`
	Defvalue string `json:"defvalue" db:"defvalue"`
}
