// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Salutation is the type-safe Go struct generated from the Salutation GoType.
type Salutation struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Salutation string `json:"salutation" db:"salutation"`
}
