// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Navbar Settings is the type-safe Go struct generated from the Navbar Settings GoType.
type Navbar Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	AppLogo string `json:"app_logo" db:"app_logo"`
	SettingsDropdown string `json:"settings_dropdown" db:"settings_dropdown"`
	HelpDropdown string `json:"help_dropdown" db:"help_dropdown"`
	SectionBreak2 string `json:"section_break_2" db:"section_break_2"`
	LogoSection string `json:"logo_section" db:"logo_section"`
	AnnouncementsSection string `json:"announcements_section" db:"announcements_section"`
	AnnouncementWidget string `json:"announcement_widget" db:"announcement_widget"`
}
