// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Email Unsubscribe is the type-safe Go struct generated from the Email Unsubscribe GoType.
type Email Unsubscribe struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Email string `json:"email" db:"email"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceName string `json:"reference_name" db:"reference_name"`
	GlobalUnsubscribe int `json:"global_unsubscribe" db:"global_unsubscribe"`
}
