// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Slack Webhook URL is the type-safe Go struct generated from the Slack Webhook URL GoType.
type Slack Webhook URL struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	WebhookName string `json:"webhook_name" db:"webhook_name"`
	WebhookUrl string `json:"webhook_url" db:"webhook_url"`
	ShowDocumentLink int `json:"show_document_link" db:"show_document_link"`
}
