// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Contact is the type-safe Go struct generated from the Contact GoType.
type Contact struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	FirstName string `json:"first_name" db:"first_name"`
	LastName string `json:"last_name" db:"last_name"`
	EmailId string `json:"email_id" db:"email_id"`
	Phone string `json:"phone" db:"phone"`
	MobileNo string `json:"mobile_no" db:"mobile_no"`
	IsPrimaryContact int `json:"is_primary_contact" db:"is_primary_contact"`
	Address string `json:"address" db:"address"`
}
