// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Error Log is the type-safe Go struct generated from the Error Log GoType.
type Error Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Seen int `json:"seen" db:"seen"`
	FingerprintStats string `json:"fingerprint_stats" db:"fingerprint_stats"`
	Method string `json:"method" db:"method"`
	Error string `json:"error" db:"error"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceName string `json:"reference_name" db:"reference_name"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	SectionBreak5 string `json:"section_break_5" db:"section_break_5"`
	TraceId string `json:"trace_id" db:"trace_id"`
	Metadata string `json:"metadata" db:"metadata"`
	Fingerprint string `json:"fingerprint" db:"fingerprint"`
	SectionBreakAyos string `json:"section_break_ayos" db:"section_break_ayos"`
}
