// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Notification Recipient is the type-safe Go struct generated from the Notification Recipient GoType.
type Notification Recipient struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Cc string `json:"cc" db:"cc"`
	Bcc string `json:"bcc" db:"bcc"`
	Condition string `json:"condition" db:"condition"`
	ReceiverByDocumentField string `json:"receiver_by_document_field" db:"receiver_by_document_field"`
	ReceiverByRole string `json:"receiver_by_role" db:"receiver_by_role"`
}
