// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Communication is the type-safe Go struct generated from the Communication GoType.
type Communication struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Subject string `json:"subject" db:"subject"`
	SectionBreak10 string `json:"section_break_10" db:"section_break_10"`
	CommunicationMedium string `json:"communication_medium" db:"communication_medium"`
	Sender string `json:"sender" db:"sender"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	Recipients string `json:"recipients" db:"recipients"`
	Cc string `json:"cc" db:"cc"`
	Bcc string `json:"bcc" db:"bcc"`
	PhoneNo string `json:"phone_no" db:"phone_no"`
	DeliveryStatus string `json:"delivery_status" db:"delivery_status"`
	SectionBreak8 string `json:"section_break_8" db:"section_break_8"`
	Content string `json:"content" db:"content"`
	StatusSection string `json:"status_section" db:"status_section"`
	TextContent string `json:"text_content" db:"text_content"`
	CommunicationType string `json:"communication_type" db:"communication_type"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	Status string `json:"status" db:"status"`
	SentOrReceived string `json:"sent_or_received" db:"sent_or_received"`
	AdditionalInfo string `json:"additional_info" db:"additional_info"`
	CommunicationDate string `json:"communication_date" db:"communication_date"`
	ReadReceipt int `json:"read_receipt" db:"read_receipt"`
	ColumnBreak14 string `json:"column_break_14" db:"column_break_14"`
	SenderFullName string `json:"sender_full_name" db:"sender_full_name"`
	ReadByRecipient int `json:"read_by_recipient" db:"read_by_recipient"`
	ReadByRecipientOn string `json:"read_by_recipient_on" db:"read_by_recipient_on"`
	ReferenceSection string `json:"reference_section" db:"reference_section"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceName string `json:"reference_name" db:"reference_name"`
	ReferenceOwner string `json:"reference_owner" db:"reference_owner"`
	EmailAccount string `json:"email_account" db:"email_account"`
	InReplyTo string `json:"in_reply_to" db:"in_reply_to"`
	User string `json:"user" db:"user"`
	ColumnBreak27 string `json:"column_break_27" db:"column_break_27"`
	UnreadNotificationSent int `json:"unread_notification_sent" db:"unread_notification_sent"`
	Seen int `json:"seen" db:"seen"`
	UserTags string `json:"_user_tags" db:"_user_tags"`
	EmailInbox string `json:"email_inbox" db:"email_inbox"`
	MessageId string `json:"message_id" db:"message_id"`
	Uid int `json:"uid" db:"uid"`
	EmailStatus string `json:"email_status" db:"email_status"`
	HasAttachment int `json:"has_attachment" db:"has_attachment"`
	EmailTemplate string `json:"email_template" db:"email_template"`
	TimelineLinksSections string `json:"timeline_links_sections" db:"timeline_links_sections"`
	TimelineLinks string `json:"timeline_links" db:"timeline_links"`
	ImapFolder string `json:"imap_folder" db:"imap_folder"`
	SendAfter string `json:"send_after" db:"send_after"`
}
