// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// System Health Report Failing Jobs is the type-safe Go struct generated from the System Health Report Failing Jobs GoType.
type System Health Report Failing Jobs struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ScheduledJobType string `json:"scheduled_job_type" db:"scheduled_job_type"`
	FailureRate string `json:"failure_rate" db:"failure_rate"`
}
