// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Website Meta Tag is the type-safe Go struct generated from the Website Meta Tag GoType.
type Website Meta Tag struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Key string `json:"key" db:"key"`
	Value string `json:"value" db:"value"`
}
