// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Session Default is the type-safe Go struct generated from the Session Default GoType.
type Session Default struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	RefDoctype string `json:"ref_doctype" db:"ref_doctype"`
}
