// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Auto Repeat Day is the type-safe Go struct generated from the Auto Repeat Day GoType.
type Auto Repeat Day struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Day string `json:"day" db:"day"`
}
