// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Email Rule is the type-safe Go struct generated from the Email Rule GoType.
type Email Rule struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	EmailId string `json:"email_id" db:"email_id"`
	IsSpam int `json:"is_spam" db:"is_spam"`
}
