// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workspace Quick List is the type-safe Go struct generated from the Workspace Quick List GoType.
type Workspace Quick List struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
	ColumnBreak1 string `json:"column_break_1" db:"column_break_1"`
	Label string `json:"label" db:"label"`
	SectionBreak4 string `json:"section_break_4" db:"section_break_4"`
	QuickListFilter string `json:"quick_list_filter" db:"quick_list_filter"`
}
