// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Module Onboarding is the type-safe Go struct generated from the Module Onboarding GoType.
type Module Onboarding struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	Module string `json:"module" db:"module"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	SectionBreak6 string `json:"section_break_6" db:"section_break_6"`
	IsComplete int `json:"is_complete" db:"is_complete"`
	Steps string `json:"steps" db:"steps"`
	AllowRoles string `json:"allow_roles" db:"allow_roles"`
}
