// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Event Notifications is the type-safe Go struct generated from the Event Notifications GoType.
type Event Notifications struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Type string `json:"type" db:"type"`
	Before int `json:"before" db:"before"`
	Interval string `json:"interval" db:"interval"`
	Time string `json:"time" db:"time"`
}
