// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Report Column is the type-safe Go struct generated from the Report Column GoType.
type Report Column struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Fieldname string `json:"fieldname" db:"fieldname"`
	Label string `json:"label" db:"label"`
	Fieldtype string `json:"fieldtype" db:"fieldtype"`
	Options string `json:"options" db:"options"`
	Width int `json:"width" db:"width"`
}
