// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// SMS Log is the type-safe Go struct generated from the SMS Log GoType.
type SMS Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SenderName string `json:"sender_name" db:"sender_name"`
	SentOn string `json:"sent_on" db:"sent_on"`
	ColumnBreak0 string `json:"column_break0" db:"column_break0"`
	Message string `json:"message" db:"message"`
	SecBreak1 string `json:"sec_break1" db:"sec_break1"`
	NoOfRequestedSms int `json:"no_of_requested_sms" db:"no_of_requested_sms"`
	RequestedNumbers string `json:"requested_numbers" db:"requested_numbers"`
	ColumnBreak1 string `json:"column_break1" db:"column_break1"`
	NoOfSentSms int `json:"no_of_sent_sms" db:"no_of_sent_sms"`
	SentTo string `json:"sent_to" db:"sent_to"`
}
