// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Notification is the type-safe Go struct generated from the Notification GoType.
type Notification struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Enabled int `json:"enabled" db:"enabled"`
	ColumnBreak2 string `json:"column_break_2" db:"column_break_2"`
	Channel string `json:"channel" db:"channel"`
	SlackWebhookUrl string `json:"slack_webhook_url" db:"slack_webhook_url"`
	Filters string `json:"filters" db:"filters"`
	Subject string `json:"subject" db:"subject"`
	DocumentType string `json:"document_type" db:"document_type"`
	IsStandard int `json:"is_standard" db:"is_standard"`
	Module string `json:"module" db:"module"`
	ColBreak1 string `json:"col_break_1" db:"col_break_1"`
	Event string `json:"event" db:"event"`
	Method string `json:"method" db:"method"`
	DateChanged string `json:"date_changed" db:"date_changed"`
	DaysInAdvance int `json:"days_in_advance" db:"days_in_advance"`
	ValueChanged string `json:"value_changed" db:"value_changed"`
	Sender string `json:"sender" db:"sender"`
	SenderEmail string `json:"sender_email" db:"sender_email"`
	SectionBreak9 string `json:"section_break_9" db:"section_break_9"`
	Condition string `json:"condition" db:"condition"`
	ColumnBreak6 string `json:"column_break_6" db:"column_break_6"`
	Html7 string `json:"html_7" db:"html_7"`
	PropertySection string `json:"property_section" db:"property_section"`
	SetPropertyAfterAlert string `json:"set_property_after_alert" db:"set_property_after_alert"`
	PropertyValue string `json:"property_value" db:"property_value"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	Recipients string `json:"recipients" db:"recipients"`
	MessageSb string `json:"message_sb" db:"message_sb"`
	Message string `json:"message" db:"message"`
	MessageExamples string `json:"message_examples" db:"message_examples"`
	ViewProperties string `json:"view_properties" db:"view_properties"`
	ColumnBreak25 string `json:"column_break_25" db:"column_break_25"`
	AttachPrint int `json:"attach_print" db:"attach_print"`
	PrintFormat string `json:"print_format" db:"print_format"`
	SendSystemNotification int `json:"send_system_notification" db:"send_system_notification"`
	NotificationType string `json:"notification_type" db:"notification_type"`
	NotificationTitle string `json:"notification_title" db:"notification_title"`
	NotificationMessage string `json:"notification_message" db:"notification_message"`
	SendToAllAssignees int `json:"send_to_all_assignees" db:"send_to_all_assignees"`
	MessageType string `json:"message_type" db:"message_type"`
	DatetimeChanged string `json:"datetime_changed" db:"datetime_changed"`
	MinutesOffset int `json:"minutes_offset" db:"minutes_offset"`
	DatetimeLastRun string `json:"datetime_last_run" db:"datetime_last_run"`
	ConditionType string `json:"condition_type" db:"condition_type"`
	FiltersEditor string `json:"filters_editor" db:"filters_editor"`
	FiltersSection string `json:"filters_section" db:"filters_section"`
	ColumnBreakLlcs string `json:"column_break_llcs" db:"column_break_llcs"`
	AttachFiles string `json:"attach_files" db:"attach_files"`
	FromAttachField string `json:"from_attach_field" db:"from_attach_field"`
}
