// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Session Default Settings is the type-safe Go struct generated from the Session Default Settings GoType.
type Session Default Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SessionDefaults string `json:"session_defaults" db:"session_defaults"`
}
