// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// File is the type-safe Go struct generated from the File GoType.
type File struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	FileName string `json:"file_name" db:"file_name"`
	FileUrl string `json:"file_url" db:"file_url"`
	FileSize int `json:"file_size" db:"file_size"`
	IsPrivate int `json:"is_private" db:"is_private"`
	AttachedToDoctype string `json:"attached_to_doctype" db:"attached_to_doctype"`
	AttachedToName string `json:"attached_to_name" db:"attached_to_name"`
}
