// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Unhandled Email is the type-safe Go struct generated from the Unhandled Email GoType.
type Unhandled Email struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	EmailAccount string `json:"email_account" db:"email_account"`
	Uid string `json:"uid" db:"uid"`
	Reason string `json:"reason" db:"reason"`
	MessageId string `json:"message_id" db:"message_id"`
	Raw string `json:"raw" db:"raw"`
}
