// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Role Permission for Page and Report is the type-safe Go struct generated from the Role Permission for Page and Report GoType.
type Role Permission for Page and Report struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SetRoleFor string `json:"set_role_for" db:"set_role_for"`
	Page string `json:"page" db:"page"`
	Report string `json:"report" db:"report"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	RolesPermission string `json:"roles_permission" db:"roles_permission"`
	RolesHtml string `json:"roles_html" db:"roles_html"`
	Roles string `json:"roles" db:"roles"`
	EnablePreparedReport int `json:"enable_prepared_report" db:"enable_prepared_report"`
}
