// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// User is the type-safe Go struct generated from the User GoType.
type User struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Email string `json:"email" db:"email"`
	FirstName string `json:"first_name" db:"first_name"`
	LastName string `json:"last_name" db:"last_name"`
	FullName string `json:"full_name" db:"full_name"`
	Username string `json:"username" db:"username"`
	Password string `json:"password" db:"password"`
	Enabled int `json:"enabled" db:"enabled"`
	UserType string `json:"user_type" db:"user_type"`
	UserImage string `json:"user_image" db:"user_image"`
	Roles string `json:"roles" db:"roles"`
}
