// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Web Page is the type-safe Go struct generated from the Web Page GoType.
type Web Page struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SectionTitle string `json:"section_title" db:"section_title"`
	Title string `json:"title" db:"title"`
	Route string `json:"route" db:"route"`
	Slideshow string `json:"slideshow" db:"slideshow"`
	Cb1 string `json:"cb1" db:"cb1"`
	Published int `json:"published" db:"published"`
	ShowTitle int `json:"show_title" db:"show_title"`
	StartDate string `json:"start_date" db:"start_date"`
	EndDate string `json:"end_date" db:"end_date"`
	Sb1 string `json:"sb1" db:"sb1"`
	ContentType string `json:"content_type" db:"content_type"`
	MainSection string `json:"main_section" db:"main_section"`
	MainSectionMd string `json:"main_section_md" db:"main_section_md"`
	MainSectionHtml string `json:"main_section_html" db:"main_section_html"`
	CustomJavascript string `json:"custom_javascript" db:"custom_javascript"`
	Javascript string `json:"javascript" db:"javascript"`
	CustomCss string `json:"custom_css" db:"custom_css"`
	InsertStyle int `json:"insert_style" db:"insert_style"`
	TextAlign string `json:"text_align" db:"text_align"`
	Css string `json:"css" db:"css"`
	Settings string `json:"settings" db:"settings"`
	SectionBreak17 string `json:"section_break_17" db:"section_break_17"`
	ShowSidebar int `json:"show_sidebar" db:"show_sidebar"`
	WebsiteSidebar string `json:"website_sidebar" db:"website_sidebar"`
	ColumnBreak20 string `json:"column_break_20" db:"column_break_20"`
	EnableComments int `json:"enable_comments" db:"enable_comments"`
	Idx int `json:"idx" db:"idx"`
	Sb2 string `json:"sb2" db:"sb2"`
	Header string `json:"header" db:"header"`
	Breadcrumbs string `json:"breadcrumbs" db:"breadcrumbs"`
	SetMetaTags string `json:"set_meta_tags" db:"set_meta_tags"`
	DynamicTemplate int `json:"dynamic_template" db:"dynamic_template"`
	PageBlocks string `json:"page_blocks" db:"page_blocks"`
	FullWidth int `json:"full_width" db:"full_width"`
	MetatagsSection string `json:"metatags_section" db:"metatags_section"`
	MetaTitle string `json:"meta_title" db:"meta_title"`
	MetaDescription string `json:"meta_description" db:"meta_description"`
	MetaImage string `json:"meta_image" db:"meta_image"`
	DynamicRoute int `json:"dynamic_route" db:"dynamic_route"`
	ContextSection string `json:"context_section" db:"context_section"`
	ContextScript string `json:"context_script" db:"context_script"`
	Module string `json:"module" db:"module"`
	ScriptingTab string `json:"scripting_tab" db:"scripting_tab"`
	PublishingDatesSection string `json:"publishing_dates_section" db:"publishing_dates_section"`
	ColumnBreak30 string `json:"column_break_30" db:"column_break_30"`
}
