// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// OAuth Client Role is the type-safe Go struct generated from the OAuth Client Role GoType.
type OAuth Client Role struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Role string `json:"role" db:"role"`
}
