// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Form Tour Step is the type-safe Go struct generated from the Form Tour Step GoType.
type Form Tour Step struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	Description string `json:"description" db:"description"`
	Fieldname string `json:"fieldname" db:"fieldname"`
	Label string `json:"label" db:"label"`
	ColumnBreak2 string `json:"column_break_2" db:"column_break_2"`
	Position string `json:"position" db:"position"`
	NextStepCondition string `json:"next_step_condition" db:"next_step_condition"`
	HasNextCondition int `json:"has_next_condition" db:"has_next_condition"`
	Fieldtype string `json:"fieldtype" db:"fieldtype"`
	IsTableField int `json:"is_table_field" db:"is_table_field"`
	SectionBreak2 string `json:"section_break_2" db:"section_break_2"`
	SectionBreak13 string `json:"section_break_13" db:"section_break_13"`
	ChildDoctype string `json:"child_doctype" db:"child_doctype"`
	ParentFieldname string `json:"parent_fieldname" db:"parent_fieldname"`
	UiTour int `json:"ui_tour" db:"ui_tour"`
	ElementSelector string `json:"element_selector" db:"element_selector"`
	ParentElementSelector string `json:"parent_element_selector" db:"parent_element_selector"`
	NextFormTour string `json:"next_form_tour" db:"next_form_tour"`
	HideButtons int `json:"hide_buttons" db:"hide_buttons"`
	NextOnClick int `json:"next_on_click" db:"next_on_click"`
	PopoverElement int `json:"popover_element" db:"popover_element"`
	OffsetX int `json:"offset_x" db:"offset_x"`
	OffsetY int `json:"offset_y" db:"offset_y"`
	ModalTrigger int `json:"modal_trigger" db:"modal_trigger"`
	OndemandDescription string `json:"ondemand_description" db:"ondemand_description"`
}
