// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Custom Role is the type-safe Go struct generated from the Custom Role GoType.
type Custom Role struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Page string `json:"page" db:"page"`
	Report string `json:"report" db:"report"`
	PermissionRules string `json:"permission_rules" db:"permission_rules"`
	Roles string `json:"roles" db:"roles"`
	Response string `json:"response" db:"response"`
	RefDoctype string `json:"ref_doctype" db:"ref_doctype"`
}
