// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Email Queue Recipient is the type-safe Go struct generated from the Email Queue Recipient GoType.
type Email Queue Recipient struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Recipient string `json:"recipient" db:"recipient"`
	Status string `json:"status" db:"status"`
	Error string `json:"error" db:"error"`
}
