// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Website Sidebar Item is the type-safe Go struct generated from the Website Sidebar Item GoType.
type Website Sidebar Item struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	Route string `json:"route" db:"route"`
	Group string `json:"group" db:"group"`
}
