// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Security Settings is the type-safe Go struct generated from the Security Settings GoType.
type Security Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SecuritytxtSection string `json:"securitytxt_section" db:"securitytxt_section"`
	PublicExpires string `json:"public_expires" db:"public_expires"`
	PublicContacts string `json:"public_contacts" db:"public_contacts"`
	PublicLanguages string `json:"public_languages" db:"public_languages"`
	PublicPolicy string `json:"public_policy" db:"public_policy"`
	SecurityTxt string `json:"security_txt" db:"security_txt"`
}
