// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Permission Inspector is the type-safe Go struct generated from the Permission Inspector GoType.
type Permission Inspector struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	RefDoctype string `json:"ref_doctype" db:"ref_doctype"`
	Docname string `json:"docname" db:"docname"`
	ColumnBreakMcqo string `json:"column_break_mcqo" db:"column_break_mcqo"`
	ColumnBreakXbrd string `json:"column_break_xbrd" db:"column_break_xbrd"`
	User string `json:"user" db:"user"`
	SectionBreakHkjp string `json:"section_break_hkjp" db:"section_break_hkjp"`
	Output string `json:"output" db:"output"`
	ColumnBreakNvaa string `json:"column_break_nvaa" db:"column_break_nvaa"`
	PermissionType string `json:"permission_type" db:"permission_type"`
}
