// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Recorder is the type-safe Go struct generated from the Recorder GoType.
type Recorder struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Path string `json:"path" db:"path"`
	Cmd string `json:"cmd" db:"cmd"`
	Duration float64 `json:"duration" db:"duration"`
	Time string `json:"time" db:"time"`
	NumberOfQueries int `json:"number_of_queries" db:"number_of_queries"`
	TimeInQueries float64 `json:"time_in_queries" db:"time_in_queries"`
	NumberOfEvents int `json:"number_of_events" db:"number_of_events"`
	ColumnBreakQo53 string `json:"column_break_qo53" db:"column_break_qo53"`
	SectionBreak1skt string `json:"section_break_1skt" db:"section_break_1skt"`
	RequestHeaders string `json:"request_headers" db:"request_headers"`
	SectionBreakSgro string `json:"section_break_sgro" db:"section_break_sgro"`
	FormDict string `json:"form_dict" db:"form_dict"`
	Method string `json:"method" db:"method"`
	SqlQueries string `json:"sql_queries" db:"sql_queries"`
	SectionBreak9jhm string `json:"section_break_9jhm" db:"section_break_9jhm"`
	EventType string `json:"event_type" db:"event_type"`
	AppsInvolved string `json:"apps_involved" db:"apps_involved"`
	SectionBreakTimeline string `json:"section_break_timeline" db:"section_break_timeline"`
	Timeline string `json:"timeline" db:"timeline"`
	SectionBreakOptn string `json:"section_break_optn" db:"section_break_optn"`
	Profile string `json:"profile" db:"profile"`
	SuggestedIndexes string `json:"suggested_indexes" db:"suggested_indexes"`
}
