// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Document Share Key is the type-safe Go struct generated from the Document Share Key GoType.
type Document Share Key struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceDocname string `json:"reference_docname" db:"reference_docname"`
	Key string `json:"key" db:"key"`
	ExpiresOn string `json:"expires_on" db:"expires_on"`
}
