// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Deleted Document is the type-safe Go struct generated from the Deleted Document GoType.
type Deleted Document struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DeletedName string `json:"deleted_name" db:"deleted_name"`
	DeletedDoctype string `json:"deleted_doctype" db:"deleted_doctype"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	Restored int `json:"restored" db:"restored"`
	NewName string `json:"new_name" db:"new_name"`
	SectionBreak6 string `json:"section_break_6" db:"section_break_6"`
	Data string `json:"data" db:"data"`
}
