// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workspace Number Card is the type-safe Go struct generated from the Workspace Number Card GoType.
type Workspace Number Card struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	NumberCardName string `json:"number_card_name" db:"number_card_name"`
	Label string `json:"label" db:"label"`
}
