// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Language is the type-safe Go struct generated from the Language GoType.
type Language struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	LanguageCode string `json:"language_code" db:"language_code"`
	LanguageName string `json:"language_name" db:"language_name"`
	Flag string `json:"flag" db:"flag"`
	BasedOn string `json:"based_on" db:"based_on"`
	Enabled int `json:"enabled" db:"enabled"`
	SectionBreakRtth string `json:"section_break_rtth" db:"section_break_rtth"`
	DateFormat string `json:"date_format" db:"date_format"`
	TimeFormat string `json:"time_format" db:"time_format"`
	NumberFormat string `json:"number_format" db:"number_format"`
	FirstDayOfTheWeek string `json:"first_day_of_the_week" db:"first_day_of_the_week"`
}
