// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Top Bar Item is the type-safe Go struct generated from the Top Bar Item GoType.
type Top Bar Item struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Label string `json:"label" db:"label"`
	ParentLabel string `json:"parent_label" db:"parent_label"`
	Url string `json:"url" db:"url"`
	Right int `json:"right" db:"right"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	OpenInNewTab int `json:"open_in_new_tab" db:"open_in_new_tab"`
}
