// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// System Console is the type-safe Go struct generated from the System Console GoType.
type System Console struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Console string `json:"console" db:"console"`
	Output string `json:"output" db:"output"`
	Commit int `json:"commit" db:"commit"`
	ExecuteSection string `json:"execute_section" db:"execute_section"`
	DatabaseProcessesSection string `json:"database_processes_section" db:"database_processes_section"`
	ShowProcesslist int `json:"show_processlist" db:"show_processlist"`
	Processlist string `json:"processlist" db:"processlist"`
	Type string `json:"type" db:"type"`
	SqlOutput string `json:"sql_output" db:"sql_output"`
}
