// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Number Card Link is the type-safe Go struct generated from the Number Card Link GoType.
type Number Card Link struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Card string `json:"card" db:"card"`
}
