// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Website Script is the type-safe Go struct generated from the Website Script GoType.
type Website Script struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Javascript string `json:"javascript" db:"javascript"`
}
