// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Web Form is the type-safe Go struct generated from the Web Form GoType.
type Web Form struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	Route string `json:"route" db:"route"`
	DocType string `json:"doc_type" db:"doc_type"`
	Module string `json:"module" db:"module"`
	IsStandard int `json:"is_standard" db:"is_standard"`
	Published int `json:"published" db:"published"`
	LoginRequired int `json:"login_required" db:"login_required"`
	AllowEdit int `json:"allow_edit" db:"allow_edit"`
	AllowMultiple int `json:"allow_multiple" db:"allow_multiple"`
	AllowDelete int `json:"allow_delete" db:"allow_delete"`
	AllowPrint int `json:"allow_print" db:"allow_print"`
	PrintFormat string `json:"print_format" db:"print_format"`
	AllowComments int `json:"allow_comments" db:"allow_comments"`
	ShowAttachments int `json:"show_attachments" db:"show_attachments"`
	AllowIncomplete int `json:"allow_incomplete" db:"allow_incomplete"`
	IntroductionText string `json:"introduction_text" db:"introduction_text"`
	WebFormFields string `json:"web_form_fields" db:"web_form_fields"`
	MaxAttachmentSize int `json:"max_attachment_size" db:"max_attachment_size"`
	ClientScript string `json:"client_script" db:"client_script"`
	ButtonLabel string `json:"button_label" db:"button_label"`
	SuccessMessage string `json:"success_message" db:"success_message"`
	SuccessUrl string `json:"success_url" db:"success_url"`
	ShowSidebar int `json:"show_sidebar" db:"show_sidebar"`
	Breadcrumbs string `json:"breadcrumbs" db:"breadcrumbs"`
	CustomCss string `json:"custom_css" db:"custom_css"`
	ApplyDocumentPermissions int `json:"apply_document_permissions" db:"apply_document_permissions"`
	ShowList int `json:"show_list" db:"show_list"`
	ListTitle string `json:"list_title" db:"list_title"`
	ListColumns string `json:"list_columns" db:"list_columns"`
	WebsiteSidebar string `json:"website_sidebar" db:"website_sidebar"`
	ListSettingMessage string `json:"list_setting_message" db:"list_setting_message"`
	CustomizationTab string `json:"customization_tab" db:"customization_tab"`
	SuccessTitle string `json:"success_title" db:"success_title"`
	BannerImage string `json:"banner_image" db:"banner_image"`
	FormTab string `json:"form_tab" db:"form_tab"`
	SectionBreak1 string `json:"section_break_1" db:"section_break_1"`
	SettingsTab string `json:"settings_tab" db:"settings_tab"`
	ColumnBreak2 string `json:"column_break_2" db:"column_break_2"`
	SectionBreak3 string `json:"section_break_3" db:"section_break_3"`
	SectionBreak4 string `json:"section_break_4" db:"section_break_4"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	SectionBreak5 string `json:"section_break_5" db:"section_break_5"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	SectionBreak6 string `json:"section_break_6" db:"section_break_6"`
	MetaSection string `json:"meta_section" db:"meta_section"`
	MetaTitle string `json:"meta_title" db:"meta_title"`
	MetaDescription string `json:"meta_description" db:"meta_description"`
	ColumnBreakKhxs string `json:"column_break_khxs" db:"column_break_khxs"`
	MetaImage string `json:"meta_image" db:"meta_image"`
	ColumnBreakVdhm string `json:"column_break_vdhm" db:"column_break_vdhm"`
	Anonymous int `json:"anonymous" db:"anonymous"`
	ConditionDescription string `json:"condition_description" db:"condition_description"`
	ConditionSection string `json:"condition_section" db:"condition_section"`
	ConditionJson string `json:"condition_json" db:"condition_json"`
	HideNavbar int `json:"hide_navbar" db:"hide_navbar"`
	HideFooter int `json:"hide_footer" db:"hide_footer"`
	AllowedEmbeddingDomains string `json:"allowed_embedding_domains" db:"allowed_embedding_domains"`
	AccessControlSection string `json:"access_control_section" db:"access_control_section"`
	FormSettingsSection string `json:"form_settings_section" db:"form_settings_section"`
	ColumnBreakHhec string `json:"column_break_hhec" db:"column_break_hhec"`
	KeyRequired int `json:"key_required" db:"key_required"`
}
