// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Security Settings Language is the type-safe Go struct generated from the Security Settings Language GoType.
type Security Settings Language struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Language string `json:"language" db:"language"`
}
