// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Permission Type is the type-safe Go struct generated from the Permission Type GoType.
type Permission Type struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	PermType string `json:"perm_type" db:"perm_type"`
	DocType string `json:"doc_type" db:"doc_type"`
}
