// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Document Naming Rule is the type-safe Go struct generated from the Document Naming Rule GoType.
type Document Naming Rule struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
	Disabled int `json:"disabled" db:"disabled"`
	Prefix string `json:"prefix" db:"prefix"`
	Counter int `json:"counter" db:"counter"`
	PrefixDigits int `json:"prefix_digits" db:"prefix_digits"`
	NamingSection string `json:"naming_section" db:"naming_section"`
	SectionBreak3 string `json:"section_break_3" db:"section_break_3"`
	Conditions string `json:"conditions" db:"conditions"`
	Priority int `json:"priority" db:"priority"`
	ColumnBreakXfqa string `json:"column_break_xfqa" db:"column_break_xfqa"`
}
