// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Webhook Data is the type-safe Go struct generated from the Webhook Data GoType.
type Webhook Data struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Fieldname string `json:"fieldname" db:"fieldname"`
	CbDocData string `json:"cb_doc_data" db:"cb_doc_data"`
	Key string `json:"key" db:"key"`
}
