// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Personal Data Download Request is the type-safe Go struct generated from the Personal Data Download Request GoType.
type Personal Data Download Request struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	User string `json:"user" db:"user"`
	UserName string `json:"user_name" db:"user_name"`
	AmendedFrom string `json:"amended_from" db:"amended_from"`
}
