// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Help Article is the type-safe Go struct generated from the Help Article GoType.
type Help Article struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	Category string `json:"category" db:"category"`
	Published int `json:"published" db:"published"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	Author string `json:"author" db:"author"`
	Level string `json:"level" db:"level"`
	SectionBreak7 string `json:"section_break_7" db:"section_break_7"`
	Content string `json:"content" db:"content"`
	Likes int `json:"likes" db:"likes"`
	Route string `json:"route" db:"route"`
	Helpful int `json:"helpful" db:"helpful"`
	Cb00 string `json:"cb_00" db:"cb_00"`
	NotHelpful int `json:"not_helpful" db:"not_helpful"`
	SectionBreakCww5 string `json:"section_break_cww5" db:"section_break_cww5"`
}
