// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workflow Document State is the type-safe Go struct generated from the Workflow Document State GoType.
type Workflow Document State struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	State string `json:"state" db:"state"`
	DocStatus string `json:"doc_status" db:"doc_status"`
	UpdateField string `json:"update_field" db:"update_field"`
	UpdateValue string `json:"update_value" db:"update_value"`
	AllowEdit string `json:"allow_edit" db:"allow_edit"`
	Message string `json:"message" db:"message"`
	NextActionEmailTemplate string `json:"next_action_email_template" db:"next_action_email_template"`
	IsOptionalState int `json:"is_optional_state" db:"is_optional_state"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	SectionBreak9 string `json:"section_break_9" db:"section_break_9"`
	WorkflowBuilderId string `json:"workflow_builder_id" db:"workflow_builder_id"`
	AvoidStatusOverride int `json:"avoid_status_override" db:"avoid_status_override"`
	SendEmail int `json:"send_email" db:"send_email"`
	EvaluateAsExpression int `json:"evaluate_as_expression" db:"evaluate_as_expression"`
}
