// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Personal Data Deletion Request is the type-safe Go struct generated from the Personal Data Deletion Request GoType.
type Personal Data Deletion Request struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Email string `json:"email" db:"email"`
	Status string `json:"status" db:"status"`
	AnonymizationMatrix string `json:"anonymization_matrix" db:"anonymization_matrix"`
	DeletionSteps string `json:"deletion_steps" db:"deletion_steps"`
}
