// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// LDAP Group Mapping is the type-safe Go struct generated from the LDAP Group Mapping GoType.
type LDAP Group Mapping struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	LdapGroup string `json:"ldap_group" db:"ldap_group"`
	ErpnextRole string `json:"erpnext_role" db:"erpnext_role"`
}
