// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Company History is the type-safe Go struct generated from the Company History GoType.
type Company History struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Year string `json:"year" db:"year"`
	Highlight string `json:"highlight" db:"highlight"`
}
