// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Calendar View is the type-safe Go struct generated from the Calendar View GoType.
type Calendar View struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	SubjectField string `json:"subject_field" db:"subject_field"`
	StartDateField string `json:"start_date_field" db:"start_date_field"`
	EndDateField string `json:"end_date_field" db:"end_date_field"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	AllDay int `json:"all_day" db:"all_day"`
}
