// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Milestone is the type-safe Go struct generated from the Milestone GoType.
type Milestone struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ReferenceType string `json:"reference_type" db:"reference_type"`
	ReferenceName string `json:"reference_name" db:"reference_name"`
	TrackField string `json:"track_field" db:"track_field"`
	Value string `json:"value" db:"value"`
	MilestoneTracker string `json:"milestone_tracker" db:"milestone_tracker"`
}
