// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// System Health Report Workers is the type-safe Go struct generated from the System Health Report Workers GoType.
type System Health Report Workers struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Queues string `json:"queues" db:"queues"`
	Count int `json:"count" db:"count"`
	Utilization string `json:"utilization" db:"utilization"`
	FailedJobs int `json:"failed_jobs" db:"failed_jobs"`
}
