// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Recorder Suggested Index is the type-safe Go struct generated from the Recorder Suggested Index GoType.
type Recorder Suggested Index struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Table string `json:"table" db:"table"`
	Column string `json:"column" db:"column"`
}
