// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// SMS Settings is the type-safe Go struct generated from the SMS Settings GoType.
type SMS Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SmsGatewayUrl string `json:"sms_gateway_url" db:"sms_gateway_url"`
	MessageParameter string `json:"message_parameter" db:"message_parameter"`
	ReceiverParameter string `json:"receiver_parameter" db:"receiver_parameter"`
	StaticParametersSection string `json:"static_parameters_section" db:"static_parameters_section"`
	Parameters string `json:"parameters" db:"parameters"`
	UsePost int `json:"use_post" db:"use_post"`
	AllowedRolesSection string `json:"allowed_roles_section" db:"allowed_roles_section"`
	AllowedRoles string `json:"allowed_roles" db:"allowed_roles"`
}
