// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Role Profile is the type-safe Go struct generated from the Role Profile GoType.
type Role Profile struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	RoleProfile string `json:"role_profile" db:"role_profile"`
	RolesHtml string `json:"roles_html" db:"roles_html"`
	Roles string `json:"roles" db:"roles"`
}
