// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Sidebar Item Group Link is the type-safe Go struct generated from the Sidebar Item Group Link GoType.
type Sidebar Item Group Link struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Report string `json:"report" db:"report"`
}
