// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Push Notification Settings is the type-safe Go struct generated from the Push Notification Settings GoType.
type Push Notification Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	EnablePushNotificationRelay int `json:"enable_push_notification_relay" db:"enable_push_notification_relay"`
	AuthenticationCredentialSection string `json:"authentication_credential_section" db:"authentication_credential_section"`
	ApiKey string `json:"api_key" db:"api_key"`
	ApiSecret string `json:"api_secret" db:"api_secret"`
	SectionBreakQgjr string `json:"section_break_qgjr" db:"section_break_qgjr"`
}
