// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Amended Document Naming Settings is the type-safe Go struct generated from the Amended Document Naming Settings GoType.
type Amended Document Naming Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Action string `json:"action" db:"action"`
	DocumentType string `json:"document_type" db:"document_type"`
}
