// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// List Filter is the type-safe Go struct generated from the List Filter GoType.
type List Filter struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	FilterName string `json:"filter_name" db:"filter_name"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ForUser string `json:"for_user" db:"for_user"`
	Filters string `json:"filters" db:"filters"`
}
