// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Google Settings is the type-safe Go struct generated from the Google Settings GoType.
type Google Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Enable int `json:"enable" db:"enable"`
	ClientId string `json:"client_id" db:"client_id"`
	ClientSecret string `json:"client_secret" db:"client_secret"`
	ApiKey string `json:"api_key" db:"api_key"`
	Sb00 string `json:"sb_00" db:"sb_00"`
	Sb01 string `json:"sb_01" db:"sb_01"`
	AppId string `json:"app_id" db:"app_id"`
	SectionBreak7 string `json:"section_break_7" db:"section_break_7"`
	GoogleDrivePickerEnabled int `json:"google_drive_picker_enabled" db:"google_drive_picker_enabled"`
}
