// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// RQ Job is the type-safe Go struct generated from the RQ Job GoType.
type RQ Job struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Queue string `json:"queue" db:"queue"`
	Status string `json:"status" db:"status"`
	JobId string `json:"job_id" db:"job_id"`
	ExcInfo string `json:"exc_info" db:"exc_info"`
	JobName string `json:"job_name" db:"job_name"`
	Arguments string `json:"arguments" db:"arguments"`
	Timeout string `json:"timeout" db:"timeout"`
	TimeTaken string `json:"time_taken" db:"time_taken"`
	StartedAt string `json:"started_at" db:"started_at"`
	EndedAt string `json:"ended_at" db:"ended_at"`
	JobInfoSection string `json:"job_info_section" db:"job_info_section"`
	JobStatusSection string `json:"job_status_section" db:"job_status_section"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	ColumnBreak11 string `json:"column_break_11" db:"column_break_11"`
	ExceptionSection string `json:"exception_section" db:"exception_section"`
}
