// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// UTM Medium is the type-safe Go struct generated from the UTM Medium GoType.
type UTM Medium struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Description string `json:"description" db:"description"`
	Slug string `json:"slug" db:"slug"`
}
