// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Access Log is the type-safe Go struct generated from the Access Log GoType.
type Access Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ExportFrom string `json:"export_from" db:"export_from"`
	User string `json:"user" db:"user"`
	Timestamp string `json:"timestamp" db:"timestamp"`
	ReferenceDocument string `json:"reference_document" db:"reference_document"`
	FileType string `json:"file_type" db:"file_type"`
	ReportName string `json:"report_name" db:"report_name"`
	Page string `json:"page" db:"page"`
	LogDataSection string `json:"log_data_section" db:"log_data_section"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	PrivateFileSection string `json:"private_file_section" db:"private_file_section"`
	ReportInformationSection string `json:"report_information_section" db:"report_information_section"`
	RawInformationLogSection string `json:"raw_information_log_section" db:"raw_information_log_section"`
	Method string `json:"method" db:"method"`
	ShowReport string `json:"show_report" db:"show_report"`
	ShowDocument string `json:"show_document" db:"show_document"`
	Filters string `json:"filters" db:"filters"`
	Columns string `json:"columns" db:"columns"`
}
