// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Data Export is the type-safe Go struct generated from the Data Export GoType.
type Data Export struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ColumnBreak2 string `json:"column_break_2" db:"column_break_2"`
	FileType string `json:"file_type" db:"file_type"`
	SectionBreak string `json:"section_break" db:"section_break"`
	FilterList string `json:"filter_list" db:"filter_list"`
	FieldsMulticheck string `json:"fields_multicheck" db:"fields_multicheck"`
	ExportWithoutMainHeader int `json:"export_without_main_header" db:"export_without_main_header"`
}
