// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Submission Queue is the type-safe Go struct generated from the Submission Queue GoType.
type Submission Queue struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	JobId string `json:"job_id" db:"job_id"`
	RefDoctype string `json:"ref_doctype" db:"ref_doctype"`
	RefDocname string `json:"ref_docname" db:"ref_docname"`
	Status string `json:"status" db:"status"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	SectionBreak8 string `json:"section_break_8" db:"section_break_8"`
	EnqueuedBy string `json:"enqueued_by" db:"enqueued_by"`
	EndedAt string `json:"ended_at" db:"ended_at"`
	CreatedAt string `json:"created_at" db:"created_at"`
	Exception string `json:"exception" db:"exception"`
}
