// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Recorder Query is the type-safe Go struct generated from the Recorder Query GoType.
type Recorder Query struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Query string `json:"query" db:"query"`
	NormalizedQuery string `json:"normalized_query" db:"normalized_query"`
	Duration float64 `json:"duration" db:"duration"`
	ExactCopies int `json:"exact_copies" db:"exact_copies"`
	NormalizedCopies int `json:"normalized_copies" db:"normalized_copies"`
	ColumnBreakQmju string `json:"column_break_qmju" db:"column_break_qmju"`
	SectionBreakDygy string `json:"section_break_dygy" db:"section_break_dygy"`
	Stack string `json:"stack" db:"stack"`
	StackHtml string `json:"stack_html" db:"stack_html"`
	SectionBreakKvkb string `json:"section_break_kvkb" db:"section_break_kvkb"`
	ExplainResult string `json:"explain_result" db:"explain_result"`
	SqlExplainHtml string `json:"sql_explain_html" db:"sql_explain_html"`
	Index int `json:"index" db:"index"`
}
