// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workspace Link is the type-safe Go struct generated from the Workspace Link GoType.
type Workspace Link struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Type string `json:"type" db:"type"`
	Label string `json:"label" db:"label"`
	Icon string `json:"icon" db:"icon"`
	Hidden int `json:"hidden" db:"hidden"`
	LinkDetailsSection string `json:"link_details_section" db:"link_details_section"`
	LinkType string `json:"link_type" db:"link_type"`
	LinkTo string `json:"link_to" db:"link_to"`
	ColumnBreak7 string `json:"column_break_7" db:"column_break_7"`
	Dependencies string `json:"dependencies" db:"dependencies"`
	OnlyFor string `json:"only_for" db:"only_for"`
	Onboard int `json:"onboard" db:"onboard"`
	IsQueryReport int `json:"is_query_report" db:"is_query_report"`
	LinkCount int `json:"link_count" db:"link_count"`
	Description string `json:"description" db:"description"`
	ReportRefDoctype string `json:"report_ref_doctype" db:"report_ref_doctype"`
}
