// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Block Module is the type-safe Go struct generated from the Block Module GoType.
type Block Module struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Module string `json:"module" db:"module"`
}
