// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Website Theme Ignore App is the type-safe Go struct generated from the Website Theme Ignore App GoType.
type Website Theme Ignore App struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	App string `json:"app" db:"app"`
}
