// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Gender is the type-safe Go struct generated from the Gender GoType.
type Gender struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Gender string `json:"gender" db:"gender"`
}
