// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DocType Layout Field is the type-safe Go struct generated from the DocType Layout Field GoType.
type DocType Layout Field struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Fieldname string `json:"fieldname" db:"fieldname"`
	Label string `json:"label" db:"label"`
}
