// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DocType Link is the type-safe Go struct generated from the DocType Link GoType.
type DocType Link struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	LinkDoctype string `json:"link_doctype" db:"link_doctype"`
	LinkFieldname string `json:"link_fieldname" db:"link_fieldname"`
	Group string `json:"group" db:"group"`
	Hidden int `json:"hidden" db:"hidden"`
	Custom int `json:"custom" db:"custom"`
	ParentDoctype string `json:"parent_doctype" db:"parent_doctype"`
	IsChildTable int `json:"is_child_table" db:"is_child_table"`
	TableFieldname string `json:"table_fieldname" db:"table_fieldname"`
}
