// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Installed Applications is the type-safe Go struct generated from the Installed Applications GoType.
type Installed Applications struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	InstalledApplications string `json:"installed_applications" db:"installed_applications"`
}
