// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Desktop Settings is the type-safe Go struct generated from the Desktop Settings GoType.
type Desktop Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	IconStyle string `json:"icon_style" db:"icon_style"`
}
