// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Event is the type-safe Go struct generated from the Event GoType.
type Event struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Details string `json:"details" db:"details"`
	Subject string `json:"subject" db:"subject"`
	EventCategory string `json:"event_category" db:"event_category"`
	EventType string `json:"event_type" db:"event_type"`
	SendReminder int `json:"send_reminder" db:"send_reminder"`
	RepeatThisEvent int `json:"repeat_this_event" db:"repeat_this_event"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	StartsOn string `json:"starts_on" db:"starts_on"`
	EndsOn string `json:"ends_on" db:"ends_on"`
	AllDay int `json:"all_day" db:"all_day"`
	SectionBreak13 string `json:"section_break_13" db:"section_break_13"`
	RepeatOn string `json:"repeat_on" db:"repeat_on"`
	RepeatTill string `json:"repeat_till" db:"repeat_till"`
	ColumnBreak16 string `json:"column_break_16" db:"column_break_16"`
	Monday int `json:"monday" db:"monday"`
	Tuesday int `json:"tuesday" db:"tuesday"`
	Wednesday int `json:"wednesday" db:"wednesday"`
	Thursday int `json:"thursday" db:"thursday"`
	Friday int `json:"friday" db:"friday"`
	Saturday int `json:"saturday" db:"saturday"`
	Sunday int `json:"sunday" db:"sunday"`
	SectionBreak8 string `json:"section_break_8" db:"section_break_8"`
	Color string `json:"color" db:"color"`
	Description string `json:"description" db:"description"`
	EventParticipants string `json:"event_participants" db:"event_participants"`
	Status string `json:"status" db:"status"`
	Sb00 string `json:"sb_00" db:"sb_00"`
	GoogleCalendarId string `json:"google_calendar_id" db:"google_calendar_id"`
	Cb00 string `json:"cb_00" db:"cb_00"`
	GoogleCalendarEventId string `json:"google_calendar_event_id" db:"google_calendar_event_id"`
	SyncWithGoogleCalendar int `json:"sync_with_google_calendar" db:"sync_with_google_calendar"`
	GoogleCalendar string `json:"google_calendar" db:"google_calendar"`
	PulledFromGoogleCalendar int `json:"pulled_from_google_calendar" db:"pulled_from_google_calendar"`
	Sender string `json:"sender" db:"sender"`
	AddVideoConferencing int `json:"add_video_conferencing" db:"add_video_conferencing"`
	GoogleMeetLink string `json:"google_meet_link" db:"google_meet_link"`
	SectionBreakJlqd string `json:"section_break_jlqd" db:"section_break_jlqd"`
	Links string `json:"links" db:"links"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ColumnBreakPjkw string `json:"column_break_pjkw" db:"column_break_pjkw"`
	ReferenceDocname string `json:"reference_docname" db:"reference_docname"`
	SectionBreakQemp string `json:"section_break_qemp" db:"section_break_qemp"`
	NotificationsTab string `json:"notifications_tab" db:"notifications_tab"`
	Notifications string `json:"notifications" db:"notifications"`
	Location string `json:"location" db:"location"`
	ParticipantsTab string `json:"participants_tab" db:"participants_tab"`
	LinksTab string `json:"links_tab" db:"links_tab"`
	Attending string `json:"attending" db:"attending"`
}
