// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Desktop Icon is the type-safe Go struct generated from the Desktop Icon GoType.
type Desktop Icon struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Label string `json:"label" db:"label"`
	Standard int `json:"standard" db:"standard"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	Link string `json:"link" db:"link"`
	Icon string `json:"icon" db:"icon"`
	Idx int `json:"idx" db:"idx"`
	LogoUrl string `json:"logo_url" db:"logo_url"`
	IconType string `json:"icon_type" db:"icon_type"`
	App string `json:"app" db:"app"`
	LinkTo string `json:"link_to" db:"link_to"`
	ParentIcon string `json:"parent_icon" db:"parent_icon"`
	Hidden int `json:"hidden" db:"hidden"`
	LinkType string `json:"link_type" db:"link_type"`
	RolesTab string `json:"roles_tab" db:"roles_tab"`
	Roles string `json:"roles" db:"roles"`
	Sidebar string `json:"sidebar" db:"sidebar"`
	IconImage string `json:"icon_image" db:"icon_image"`
	RestrictRemoval int `json:"restrict_removal" db:"restrict_removal"`
	BgColor string `json:"bg_color" db:"bg_color"`
}
