// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// ToDo is the type-safe Go struct generated from the ToDo GoType.
type ToDo struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DescriptionAndStatus string `json:"description_and_status" db:"description_and_status"`
	Status string `json:"status" db:"status"`
	Priority string `json:"priority" db:"priority"`
	ColumnBreak2 string `json:"column_break_2" db:"column_break_2"`
	Color string `json:"color" db:"color"`
	Date string `json:"date" db:"date"`
	DescriptionSection string `json:"description_section" db:"description_section"`
	Description string `json:"description" db:"description"`
	SectionBreak6 string `json:"section_break_6" db:"section_break_6"`
	ReferenceType string `json:"reference_type" db:"reference_type"`
	ReferenceName string `json:"reference_name" db:"reference_name"`
	ColumnBreak10 string `json:"column_break_10" db:"column_break_10"`
	Role string `json:"role" db:"role"`
	AssignedBy string `json:"assigned_by" db:"assigned_by"`
	AssignedByFullName string `json:"assigned_by_full_name" db:"assigned_by_full_name"`
	Sender string `json:"sender" db:"sender"`
	AssignmentRule string `json:"assignment_rule" db:"assignment_rule"`
	AllocatedTo string `json:"allocated_to" db:"allocated_to"`
}
