// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Help Category is the type-safe Go struct generated from the Help Category GoType.
type Help Category struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	CategoryName string `json:"category_name" db:"category_name"`
	CategoryDescription string `json:"category_description" db:"category_description"`
	Published int `json:"published" db:"published"`
	HelpArticles int `json:"help_articles" db:"help_articles"`
	Route string `json:"route" db:"route"`
}
