// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Email Group is the type-safe Go struct generated from the Email Group GoType.
type Email Group struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	TotalSubscribers int `json:"total_subscribers" db:"total_subscribers"`
	ConfirmationEmailTemplate string `json:"confirmation_email_template" db:"confirmation_email_template"`
	WelcomeEmailTemplate string `json:"welcome_email_template" db:"welcome_email_template"`
	SignUpAndConfirmationSection string `json:"sign_up_and_confirmation_section" db:"sign_up_and_confirmation_section"`
	WelcomeUrl string `json:"welcome_url" db:"welcome_url"`
	AddQueryParameters int `json:"add_query_parameters" db:"add_query_parameters"`
}
