// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Milestone Tracker is the type-safe Go struct generated from the Milestone Tracker GoType.
type Milestone Tracker struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
	TrackField string `json:"track_field" db:"track_field"`
	Disabled int `json:"disabled" db:"disabled"`
}
