// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Website Route Meta is the type-safe Go struct generated from the Website Route Meta GoType.
type Website Route Meta struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	MetaTags string `json:"meta_tags" db:"meta_tags"`
}
