// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Currency is the type-safe Go struct generated from the Currency GoType.
type Currency struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	CurrencyName string `json:"currency_name" db:"currency_name"`
	Enabled int `json:"enabled" db:"enabled"`
	Fraction string `json:"fraction" db:"fraction"`
	FractionUnits int `json:"fraction_units" db:"fraction_units"`
	SmallestCurrencyFractionValue float64 `json:"smallest_currency_fraction_value" db:"smallest_currency_fraction_value"`
	Symbol string `json:"symbol" db:"symbol"`
	NumberFormat string `json:"number_format" db:"number_format"`
	SymbolOnRight int `json:"symbol_on_right" db:"symbol_on_right"`
}
