// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Contact Email is the type-safe Go struct generated from the Contact Email GoType.
type Contact Email struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	EmailId string `json:"email_id" db:"email_id"`
	IsPrimary int `json:"is_primary" db:"is_primary"`
}
