// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Custom Field is the type-safe Go struct generated from the Custom Field GoType.
type Custom Field struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Dt string `json:"dt" db:"dt"`
	Label string `json:"label" db:"label"`
	LabelHelp string `json:"label_help" db:"label_help"`
	Fieldname string `json:"fieldname" db:"fieldname"`
	InsertAfter string `json:"insert_after" db:"insert_after"`
	ColumnBreak6 string `json:"column_break_6" db:"column_break_6"`
	Fieldtype string `json:"fieldtype" db:"fieldtype"`
	Precision string `json:"precision" db:"precision"`
	Options string `json:"options" db:"options"`
	FetchFrom string `json:"fetch_from" db:"fetch_from"`
	FetchIfEmpty int `json:"fetch_if_empty" db:"fetch_if_empty"`
	OptionsHelp string `json:"options_help" db:"options_help"`
	SectionBreak11 string `json:"section_break_11" db:"section_break_11"`
	Collapsible int `json:"collapsible" db:"collapsible"`
	CollapsibleDependsOn string `json:"collapsible_depends_on" db:"collapsible_depends_on"`
	Default string `json:"default" db:"default"`
	DependsOn string `json:"depends_on" db:"depends_on"`
	Description string `json:"description" db:"description"`
	Permlevel int `json:"permlevel" db:"permlevel"`
	Width string `json:"width" db:"width"`
	Columns int `json:"columns" db:"columns"`
	Properties string `json:"properties" db:"properties"`
	Reqd int `json:"reqd" db:"reqd"`
	Unique int `json:"unique" db:"unique"`
	IsVirtual int `json:"is_virtual" db:"is_virtual"`
	ReadOnly int `json:"read_only" db:"read_only"`
	IgnoreUserPermissions int `json:"ignore_user_permissions" db:"ignore_user_permissions"`
	Hidden int `json:"hidden" db:"hidden"`
	PrintHide int `json:"print_hide" db:"print_hide"`
	PrintHideIfNoValue int `json:"print_hide_if_no_value" db:"print_hide_if_no_value"`
	PrintWidth string `json:"print_width" db:"print_width"`
	Alignment string `json:"alignment" db:"alignment"`
	NoCopy int `json:"no_copy" db:"no_copy"`
	AllowOnSubmit int `json:"allow_on_submit" db:"allow_on_submit"`
	InListView int `json:"in_list_view" db:"in_list_view"`
	InStandardFilter int `json:"in_standard_filter" db:"in_standard_filter"`
	InGlobalSearch int `json:"in_global_search" db:"in_global_search"`
	Bold int `json:"bold" db:"bold"`
	ReportHide int `json:"report_hide" db:"report_hide"`
	SearchIndex int `json:"search_index" db:"search_index"`
	IgnoreXssFilter int `json:"ignore_xss_filter" db:"ignore_xss_filter"`
	Translatable int `json:"translatable" db:"translatable"`
	Length int `json:"length" db:"length"`
	MandatoryDependsOn string `json:"mandatory_depends_on" db:"mandatory_depends_on"`
	ReadOnlyDependsOn string `json:"read_only_depends_on" db:"read_only_depends_on"`
	AllowInQuickEntry int `json:"allow_in_quick_entry" db:"allow_in_quick_entry"`
	AllowBulkEdit int `json:"allow_bulk_edit" db:"allow_bulk_edit"`
	InPreview int `json:"in_preview" db:"in_preview"`
	HideSeconds int `json:"hide_seconds" db:"hide_seconds"`
	HideDays int `json:"hide_days" db:"hide_days"`
	HideBorder int `json:"hide_border" db:"hide_border"`
	NonNegative int `json:"non_negative" db:"non_negative"`
	Module string `json:"module" db:"module"`
	IsSystemGenerated int `json:"is_system_generated" db:"is_system_generated"`
	SortOptions int `json:"sort_options" db:"sort_options"`
	LinkFilters string `json:"link_filters" db:"link_filters"`
	ShowDashboard int `json:"show_dashboard" db:"show_dashboard"`
	Placeholder string `json:"placeholder" db:"placeholder"`
	ButtonColor string `json:"button_color" db:"button_color"`
	SetOnlyOnce int `json:"set_only_once" db:"set_only_once"`
	Mask int `json:"mask" db:"mask"`
}
