// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Document Naming Rule Condition is the type-safe Go struct generated from the Document Naming Rule Condition GoType.
type Document Naming Rule Condition struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Field string `json:"field" db:"field"`
	Condition string `json:"condition" db:"condition"`
	Value string `json:"value" db:"value"`
}
