// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Integration Request is the type-safe Go struct generated from the Integration Request GoType.
type Integration Request struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
}
