// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Geolocation Settings is the type-safe Go struct generated from the Geolocation Settings GoType.
type Geolocation Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Provider string `json:"provider" db:"provider"`
	ApiKey string `json:"api_key" db:"api_key"`
	EnableAddressAutocompletion int `json:"enable_address_autocompletion" db:"enable_address_autocompletion"`
	BaseUrl string `json:"base_url" db:"base_url"`
}
