// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// OAuth Settings is the type-safe Go struct generated from the OAuth Settings GoType.
type OAuth Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ResourceServerSection string `json:"resource_server_section" db:"resource_server_section"`
	ResourceName string `json:"resource_name" db:"resource_name"`
	ColumnBreakZyte string `json:"column_break_zyte" db:"column_break_zyte"`
	ResourceDocumentation string `json:"resource_documentation" db:"resource_documentation"`
	ResourcePolicyUri string `json:"resource_policy_uri" db:"resource_policy_uri"`
	ResourceTosUri string `json:"resource_tos_uri" db:"resource_tos_uri"`
	AuthorizationServerSection string `json:"authorization_server_section" db:"authorization_server_section"`
	ShowAuthServerMetadata int `json:"show_auth_server_metadata" db:"show_auth_server_metadata"`
	ShowProtectedResourceMetadata int `json:"show_protected_resource_metadata" db:"show_protected_resource_metadata"`
	ScopesSupported string `json:"scopes_supported" db:"scopes_supported"`
	EnableDynamicClientRegistration int `json:"enable_dynamic_client_registration" db:"enable_dynamic_client_registration"`
	SkipAuthorization int `json:"skip_authorization" db:"skip_authorization"`
	ShowSocialLoginKeyAsAuthorizationServer int `json:"show_social_login_key_as_authorization_server" db:"show_social_login_key_as_authorization_server"`
	ColumnBreakOgmd string `json:"column_break_ogmd" db:"column_break_ogmd"`
	AuthorizationTab string `json:"authorization_tab" db:"authorization_tab"`
	ResourceTab string `json:"resource_tab" db:"resource_tab"`
	ConfigSection string `json:"config_section" db:"config_section"`
	ColumnBreakWlfj string `json:"column_break_wlfj" db:"column_break_wlfj"`
	AllowedPublicClientOrigins string `json:"allowed_public_client_origins" db:"allowed_public_client_origins"`
}
