// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DocType is the type-safe Go struct generated from the DocType GoType.
type DocType struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Name string `json:"name" db:"name"`
	Module string `json:"module" db:"module"`
	Istable int `json:"istable" db:"istable"`
	Issingle int `json:"issingle" db:"issingle"`
	IsSubmittable int `json:"is_submittable" db:"is_submittable"`
	Fields string `json:"fields" db:"fields"`
	Permissions string `json:"permissions" db:"permissions"`
	Description string `json:"description" db:"description"`
}
