// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Version is the type-safe Go struct generated from the Version GoType.
type Version struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	RefDoctype string `json:"ref_doctype" db:"ref_doctype"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	Docname string `json:"docname" db:"docname"`
	Data string `json:"data" db:"data"`
	SectionBreak4 string `json:"section_break_4" db:"section_break_4"`
	TableHtml string `json:"table_html" db:"table_html"`
}
