// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// IMAP Folder is the type-safe Go struct generated from the IMAP Folder GoType.
type IMAP Folder struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	FolderName string `json:"folder_name" db:"folder_name"`
	AppendTo string `json:"append_to" db:"append_to"`
	Uidvalidity string `json:"uidvalidity" db:"uidvalidity"`
	Uidnext string `json:"uidnext" db:"uidnext"`
}
