// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// System Health Report Tables is the type-safe Go struct generated from the System Health Report Tables GoType.
type System Health Report Tables struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Table string `json:"table" db:"table"`
	Size float64 `json:"size" db:"size"`
}
