// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// API Request Log is the type-safe Go struct generated from the API Request Log GoType.
type API Request Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Path string `json:"path" db:"path"`
	User string `json:"user" db:"user"`
	Method string `json:"method" db:"method"`
}
