// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// View Log is the type-safe Go struct generated from the View Log GoType.
type View Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ViewedBy string `json:"viewed_by" db:"viewed_by"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceName string `json:"reference_name" db:"reference_name"`
}
