// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DuckDB Sync Item is the type-safe Go struct generated from the DuckDB Sync Item GoType.
type DuckDB Sync Item struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Table string `json:"table" db:"table"`
	ColumnBreakKodk string `json:"column_break_kodk" db:"column_break_kodk"`
	Synced int `json:"synced" db:"synced"`
}
