// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Module Profile is the type-safe Go struct generated from the Module Profile GoType.
type Module Profile struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ModuleProfileName string `json:"module_profile_name" db:"module_profile_name"`
	ModuleHtml string `json:"module_html" db:"module_html"`
	BlockModules string `json:"block_modules" db:"block_modules"`
}
