// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workflow State is the type-safe Go struct generated from the Workflow State GoType.
type Workflow State struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	WorkflowStateName string `json:"workflow_state_name" db:"workflow_state_name"`
	Icon string `json:"icon" db:"icon"`
	Style string `json:"style" db:"style"`
}
