// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Website Sidebar is the type-safe Go struct generated from the Website Sidebar GoType.
type Website Sidebar struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	SidebarItems string `json:"sidebar_items" db:"sidebar_items"`
}
