// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Assignment Rule is the type-safe Go struct generated from the Assignment Rule GoType.
type Assignment Rule struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocumentType string `json:"document_type" db:"document_type"`
	Priority int `json:"priority" db:"priority"`
	Disabled int `json:"disabled" db:"disabled"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	Description string `json:"description" db:"description"`
	AssignmentRulesSection string `json:"assignment_rules_section" db:"assignment_rules_section"`
	AssignCondition string `json:"assign_condition" db:"assign_condition"`
	ColumnBreak6 string `json:"column_break_6" db:"column_break_6"`
	UnassignCondition string `json:"unassign_condition" db:"unassign_condition"`
	AssignToUsersSection string `json:"assign_to_users_section" db:"assign_to_users_section"`
	Rule string `json:"rule" db:"rule"`
	Users string `json:"users" db:"users"`
	LastUser string `json:"last_user" db:"last_user"`
	SectionBreak10 string `json:"section_break_10" db:"section_break_10"`
	CloseCondition string `json:"close_condition" db:"close_condition"`
	Sb string `json:"sb" db:"sb"`
	AssignmentDays string `json:"assignment_days" db:"assignment_days"`
	DueDateBasedOn string `json:"due_date_based_on" db:"due_date_based_on"`
	Field string `json:"field" db:"field"`
	CurrentIndex int `json:"current_index" db:"current_index"`
	ColumnBreakMkgo string `json:"column_break_mkgo" db:"column_break_mkgo"`
	WeightedUsers string `json:"weighted_users" db:"weighted_users"`
}
