// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Discussion Reply is the type-safe Go struct generated from the Discussion Reply GoType.
type Discussion Reply struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Reply string `json:"reply" db:"reply"`
	Topic string `json:"topic" db:"topic"`
}
