// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Dashboard Chart Field is the type-safe Go struct generated from the Dashboard Chart Field GoType.
type Dashboard Chart Field struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	YField string `json:"y_field" db:"y_field"`
	Color string `json:"color" db:"color"`
}
