// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Webhook is the type-safe Go struct generated from the Webhook GoType.
type Webhook struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SbDocEvents string `json:"sb_doc_events" db:"sb_doc_events"`
	WebhookDoctype string `json:"webhook_doctype" db:"webhook_doctype"`
	CbDocEvents string `json:"cb_doc_events" db:"cb_doc_events"`
	WebhookDocevent string `json:"webhook_docevent" db:"webhook_docevent"`
	SbCondition string `json:"sb_condition" db:"sb_condition"`
	Condition string `json:"condition" db:"condition"`
	CbCondition string `json:"cb_condition" db:"cb_condition"`
	HtmlCondition string `json:"html_condition" db:"html_condition"`
	SbWebhook string `json:"sb_webhook" db:"sb_webhook"`
	RequestUrl string `json:"request_url" db:"request_url"`
	SbWebhookHeaders string `json:"sb_webhook_headers" db:"sb_webhook_headers"`
	WebhookHeaders string `json:"webhook_headers" db:"webhook_headers"`
	SbWebhookData string `json:"sb_webhook_data" db:"sb_webhook_data"`
	WebhookData string `json:"webhook_data" db:"webhook_data"`
	CbWebhook string `json:"cb_webhook" db:"cb_webhook"`
	RequestStructure string `json:"request_structure" db:"request_structure"`
	WebhookJson string `json:"webhook_json" db:"webhook_json"`
	SbSecurity string `json:"sb_security" db:"sb_security"`
	EnableSecurity int `json:"enable_security" db:"enable_security"`
	WebhookSecret string `json:"webhook_secret" db:"webhook_secret"`
	Enabled int `json:"enabled" db:"enabled"`
	RequestMethod string `json:"request_method" db:"request_method"`
	IsDynamicUrl int `json:"is_dynamic_url" db:"is_dynamic_url"`
	Timeout int `json:"timeout" db:"timeout"`
	BackgroundJobsQueue string `json:"background_jobs_queue" db:"background_jobs_queue"`
}
