// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Document Follow is the type-safe Go struct generated from the Document Follow GoType.
type Document Follow struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	RefDoctype string `json:"ref_doctype" db:"ref_doctype"`
	RefDocname string `json:"ref_docname" db:"ref_docname"`
	User string `json:"user" db:"user"`
}
