// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Customize Form is the type-safe Go struct generated from the Customize Form GoType.
type Customize Form struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	NamingRule string `json:"naming_rule" db:"naming_rule"`
	DocType string `json:"doc_type" db:"doc_type"`
	Properties string `json:"properties" db:"properties"`
	Label string `json:"label" db:"label"`
	DefaultPrintFormat string `json:"default_print_format" db:"default_print_format"`
	MaxAttachments int `json:"max_attachments" db:"max_attachments"`
	HideToolbar int `json:"hide_toolbar" db:"hide_toolbar"`
	AllowCopy int `json:"allow_copy" db:"allow_copy"`
	Istable int `json:"istable" db:"istable"`
	EditableGrid int `json:"editable_grid" db:"editable_grid"`
	QuickEntry int `json:"quick_entry" db:"quick_entry"`
	TrackChanges int `json:"track_changes" db:"track_changes"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	TitleField string `json:"title_field" db:"title_field"`
	ImageField string `json:"image_field" db:"image_field"`
	SearchFields string `json:"search_fields" db:"search_fields"`
	SectionBreak8 string `json:"section_break_8" db:"section_break_8"`
	SortField string `json:"sort_field" db:"sort_field"`
	ColumnBreak10 string `json:"column_break_10" db:"column_break_10"`
	SortOrder string `json:"sort_order" db:"sort_order"`
	FieldsSectionBreak string `json:"fields_section_break" db:"fields_section_break"`
	Fields string `json:"fields" db:"fields"`
	TrackViews int `json:"track_views" db:"track_views"`
	AllowAutoRepeat int `json:"allow_auto_repeat" db:"allow_auto_repeat"`
	AllowImport int `json:"allow_import" db:"allow_import"`
	AllowBulkEdit int `json:"allow_bulk_edit" db:"allow_bulk_edit"`
	SubjectField string `json:"subject_field" db:"subject_field"`
	SenderField string `json:"sender_field" db:"sender_field"`
	EmailAppendTo int `json:"email_append_to" db:"email_append_to"`
	ShowPreviewPopup int `json:"show_preview_popup" db:"show_preview_popup"`
	ViewSettingsSection string `json:"view_settings_section" db:"view_settings_section"`
	ColumnBreak29 string `json:"column_break_29" db:"column_break_29"`
	EmailSettingsSection string `json:"email_settings_section" db:"email_settings_section"`
	DocumentLinksSection string `json:"document_links_section" db:"document_links_section"`
	Links string `json:"links" db:"links"`
	DocumentActionsSection string `json:"document_actions_section" db:"document_actions_section"`
	Actions string `json:"actions" db:"actions"`
	DefaultEmailTemplate string `json:"default_email_template" db:"default_email_template"`
	ColumnBreak26 string `json:"column_break_26" db:"column_break_26"`
	NamingSection string `json:"naming_section" db:"naming_section"`
	Autoname string `json:"autoname" db:"autoname"`
	DocumentStatesSection string `json:"document_states_section" db:"document_states_section"`
	States string `json:"states" db:"states"`
	ShowTitleFieldInLink int `json:"show_title_field_in_link" db:"show_title_field_in_link"`
	TranslatedDoctype int `json:"translated_doctype" db:"translated_doctype"`
	FormSettingsSection string `json:"form_settings_section" db:"form_settings_section"`
	ColumnBreak21 string `json:"column_break_21" db:"column_break_21"`
	MakeAttachmentsPublic int `json:"make_attachments_public" db:"make_attachments_public"`
	QueueInBackground int `json:"queue_in_background" db:"queue_in_background"`
	DefaultView string `json:"default_view" db:"default_view"`
	ForceReRouteToDefaultView int `json:"force_re_route_to_default_view" db:"force_re_route_to_default_view"`
	IsCalendarAndGantt int `json:"is_calendar_and_gantt" db:"is_calendar_and_gantt"`
	FormBuilder string `json:"form_builder" db:"form_builder"`
	FormTab string `json:"form_tab" db:"form_tab"`
	LinkFilters string `json:"link_filters" db:"link_filters"`
	DetailsTab string `json:"details_tab" db:"details_tab"`
	SenderNameField string `json:"sender_name_field" db:"sender_name_field"`
	GridPageLength int `json:"grid_page_length" db:"grid_page_length"`
	ProtectAttachedFiles int `json:"protect_attached_files" db:"protect_attached_files"`
	RecipientAccountField string `json:"recipient_account_field" db:"recipient_account_field"`
	RowsThresholdForGridSearch int `json:"rows_threshold_for_grid_search" db:"rows_threshold_for_grid_search"`
	ShowNameInGlobalSearch int `json:"show_name_in_global_search" db:"show_name_in_global_search"`
}
