// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Website Theme is the type-safe Go struct generated from the Website Theme GoType.
type Website Theme struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Theme string `json:"theme" db:"theme"`
	Module string `json:"module" db:"module"`
	Custom int `json:"custom" db:"custom"`
	ThemeScss string `json:"theme_scss" db:"theme_scss"`
	ThemeUrl string `json:"theme_url" db:"theme_url"`
	CustomJsSection string `json:"custom_js_section" db:"custom_js_section"`
	Js string `json:"js" db:"js"`
	BootstrapThemeSection string `json:"bootstrap_theme_section" db:"bootstrap_theme_section"`
	GoogleFont string `json:"google_font" db:"google_font"`
	FontSize string `json:"font_size" db:"font_size"`
	PrimaryColor string `json:"primary_color" db:"primary_color"`
	TextColor string `json:"text_color" db:"text_color"`
	DarkColor string `json:"dark_color" db:"dark_color"`
	BackgroundColor string `json:"background_color" db:"background_color"`
	StylesheetSection string `json:"stylesheet_section" db:"stylesheet_section"`
	CustomScss string `json:"custom_scss" db:"custom_scss"`
	LightColor string `json:"light_color" db:"light_color"`
	FontProperties string `json:"font_properties" db:"font_properties"`
	ButtonRoundedCorners int `json:"button_rounded_corners" db:"button_rounded_corners"`
	ButtonShadows int `json:"button_shadows" db:"button_shadows"`
	ButtonGradients int `json:"button_gradients" db:"button_gradients"`
	ColumnBreak11 string `json:"column_break_11" db:"column_break_11"`
	CustomOverrides string `json:"custom_overrides" db:"custom_overrides"`
	IgnoredApps string `json:"ignored_apps" db:"ignored_apps"`
}
