// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// EmailAccount is the type-safe Go struct generated from the EmailAccount GoType.
type EmailAccount struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	EmailId string `json:"email_id" db:"email_id"`
	EmailAccountName string `json:"email_account_name" db:"email_account_name"`
	Service string `json:"service" db:"service"`
	SmtpServer string `json:"smtp_server" db:"smtp_server"`
	SmtpPort int `json:"smtp_port" db:"smtp_port"`
	UseTls int `json:"use_tls" db:"use_tls"`
	UseSsl int `json:"use_ssl" db:"use_ssl"`
	EnableIncoming int `json:"enable_incoming" db:"enable_incoming"`
	EnableOutgoing int `json:"enable_outgoing" db:"enable_outgoing"`
	DefaultOutgoing int `json:"default_outgoing" db:"default_outgoing"`
}
