// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// RQ Worker is the type-safe Go struct generated from the RQ Worker GoType.
type RQ Worker struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	WorkerName string `json:"worker_name" db:"worker_name"`
	Status string `json:"status" db:"status"`
	CurrentJobId string `json:"current_job_id" db:"current_job_id"`
	Pid string `json:"pid" db:"pid"`
	LastHeartbeat string `json:"last_heartbeat" db:"last_heartbeat"`
	BirthDate string `json:"birth_date" db:"birth_date"`
	SuccessfulJobCount int `json:"successful_job_count" db:"successful_job_count"`
	FailedJobCount int `json:"failed_job_count" db:"failed_job_count"`
	TotalWorkingTime string `json:"total_working_time" db:"total_working_time"`
	Queue string `json:"queue" db:"queue"`
	QueueType string `json:"queue_type" db:"queue_type"`
	WorkerInformationSection string `json:"worker_information_section" db:"worker_information_section"`
	StatisticsSection string `json:"statistics_section" db:"statistics_section"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	ColumnBreak12 string `json:"column_break_12" db:"column_break_12"`
	UtilizationPercent string `json:"utilization_percent" db:"utilization_percent"`
}
