// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Social Link Settings is the type-safe Go struct generated from the Social Link Settings GoType.
type Social Link Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	SocialLinkType string `json:"social_link_type" db:"social_link_type"`
	Color string `json:"color" db:"color"`
	BackgroundColor string `json:"background_color" db:"background_color"`
}
