// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Webhook Request Log is the type-safe Go struct generated from the Webhook Request Log GoType.
type Webhook Request Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Url string `json:"url" db:"url"`
	Headers string `json:"headers" db:"headers"`
	Response string `json:"response" db:"response"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	Data string `json:"data" db:"data"`
	User string `json:"user" db:"user"`
	ReferenceDocument string `json:"reference_document" db:"reference_document"`
	Error string `json:"error" db:"error"`
	Webhook string `json:"webhook" db:"webhook"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
}
