// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// OAuth Authorization Code is the type-safe Go struct generated from the OAuth Authorization Code GoType.
type OAuth Authorization Code struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Client string `json:"client" db:"client"`
	User string `json:"user" db:"user"`
	Scopes string `json:"scopes" db:"scopes"`
	AuthorizationCode string `json:"authorization_code" db:"authorization_code"`
	ExpirationTime string `json:"expiration_time" db:"expiration_time"`
	RedirectUriBoundToAuthorizationCode string `json:"redirect_uri_bound_to_authorization_code" db:"redirect_uri_bound_to_authorization_code"`
	Validity string `json:"validity" db:"validity"`
	Nonce string `json:"nonce" db:"nonce"`
	CodeChallenge string `json:"code_challenge" db:"code_challenge"`
	CodeChallengeMethod string `json:"code_challenge_method" db:"code_challenge_method"`
}
