// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Auto Email Report is the type-safe Go struct generated from the Auto Email Report GoType.
type Auto Email Report struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Report string `json:"report" db:"report"`
	User string `json:"user" db:"user"`
	Enabled int `json:"enabled" db:"enabled"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	ReportType string `json:"report_type" db:"report_type"`
	FilterData string `json:"filter_data" db:"filter_data"`
	SendIfData int `json:"send_if_data" db:"send_if_data"`
	DataModifiedTill int `json:"data_modified_till" db:"data_modified_till"`
	NoOfRows int `json:"no_of_rows" db:"no_of_rows"`
	ReportFilters string `json:"report_filters" db:"report_filters"`
	FiltersDisplay string `json:"filters_display" db:"filters_display"`
	Filters string `json:"filters" db:"filters"`
	FilterMeta string `json:"filter_meta" db:"filter_meta"`
	DynamicReportFiltersSection string `json:"dynamic_report_filters_section" db:"dynamic_report_filters_section"`
	FromDateField string `json:"from_date_field" db:"from_date_field"`
	ToDateField string `json:"to_date_field" db:"to_date_field"`
	ColumnBreak17 string `json:"column_break_17" db:"column_break_17"`
	DynamicDatePeriod string `json:"dynamic_date_period" db:"dynamic_date_period"`
	EmailSettings string `json:"email_settings" db:"email_settings"`
	EmailTo string `json:"email_to" db:"email_to"`
	DayOfWeek string `json:"day_of_week" db:"day_of_week"`
	ColumnBreak13 string `json:"column_break_13" db:"column_break_13"`
	Frequency string `json:"frequency" db:"frequency"`
	Format string `json:"format" db:"format"`
	SectionBreak15 string `json:"section_break_15" db:"section_break_15"`
	Description string `json:"description" db:"description"`
	ReferenceReport string `json:"reference_report" db:"reference_report"`
	Sender string `json:"sender" db:"sender"`
	UseFirstDayOfPeriod int `json:"use_first_day_of_period" db:"use_first_day_of_period"`
}
