// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Print Settings is the type-safe Go struct generated from the Print Settings GoType.
type Print Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	PdfSettings string `json:"pdf_settings" db:"pdf_settings"`
	SendPrintAsPdf int `json:"send_print_as_pdf" db:"send_print_as_pdf"`
	RepeatHeaderFooter int `json:"repeat_header_footer" db:"repeat_header_footer"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	PdfPageSize string `json:"pdf_page_size" db:"pdf_page_size"`
	ViewLinkInEmail string `json:"view_link_in_email" db:"view_link_in_email"`
	WithLetterhead int `json:"with_letterhead" db:"with_letterhead"`
	AllowPrintForDraft int `json:"allow_print_for_draft" db:"allow_print_for_draft"`
	ColumnBreak10 string `json:"column_break_10" db:"column_break_10"`
	AddDraftHeading int `json:"add_draft_heading" db:"add_draft_heading"`
	AllowPageBreakInsideTables int `json:"allow_page_break_inside_tables" db:"allow_page_break_inside_tables"`
	AllowPrintForCancelled int `json:"allow_print_for_cancelled" db:"allow_print_for_cancelled"`
	ServerPrinter string `json:"server_printer" db:"server_printer"`
	EnablePrintServer int `json:"enable_print_server" db:"enable_print_server"`
	RawPrintingSection string `json:"raw_printing_section" db:"raw_printing_section"`
	EnableRawPrinting int `json:"enable_raw_printing" db:"enable_raw_printing"`
	PrintStyleSection string `json:"print_style_section" db:"print_style_section"`
	PrintStyle string `json:"print_style" db:"print_style"`
	PrintStylePreview string `json:"print_style_preview" db:"print_style_preview"`
	SectionBreak8 string `json:"section_break_8" db:"section_break_8"`
	Font string `json:"font" db:"font"`
	FontSize float64 `json:"font_size" db:"font_size"`
	PdfPageHeight float64 `json:"pdf_page_height" db:"pdf_page_height"`
	PdfPageWidth float64 `json:"pdf_page_width" db:"pdf_page_width"`
	PdfGenerator string `json:"pdf_generator" db:"pdf_generator"`
}
