// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workspace is the type-safe Go struct generated from the Workspace GoType.
type Workspace struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Label string `json:"label" db:"label"`
	TabBreak2 string `json:"tab_break_2" db:"tab_break_2"`
	Charts string `json:"charts" db:"charts"`
	Shortcuts string `json:"shortcuts" db:"shortcuts"`
	RestrictToDomain string `json:"restrict_to_domain" db:"restrict_to_domain"`
	Module string `json:"module" db:"module"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	TabBreak15 string `json:"tab_break_15" db:"tab_break_15"`
	TabBreak18 string `json:"tab_break_18" db:"tab_break_18"`
	ForUser string `json:"for_user" db:"for_user"`
	HideCustom int `json:"hide_custom" db:"hide_custom"`
	Icon string `json:"icon" db:"icon"`
	Links string `json:"links" db:"links"`
	Public int `json:"public" db:"public"`
	Title string `json:"title" db:"title"`
	ParentPage string `json:"parent_page" db:"parent_page"`
	Content string `json:"content" db:"content"`
	SequenceId float64 `json:"sequence_id" db:"sequence_id"`
	Roles string `json:"roles" db:"roles"`
	RolesTab string `json:"roles_tab" db:"roles_tab"`
	QuickListsTab string `json:"quick_lists_tab" db:"quick_lists_tab"`
	QuickLists string `json:"quick_lists" db:"quick_lists"`
	IsHidden int `json:"is_hidden" db:"is_hidden"`
	NumberCardsTab string `json:"number_cards_tab" db:"number_cards_tab"`
	NumberCards string `json:"number_cards" db:"number_cards"`
	CustomBlocksTab string `json:"custom_blocks_tab" db:"custom_blocks_tab"`
	CustomBlocks string `json:"custom_blocks" db:"custom_blocks"`
	IndicatorColor string `json:"indicator_color" db:"indicator_color"`
	App string `json:"app" db:"app"`
	Type string `json:"type" db:"type"`
	LinkType string `json:"link_type" db:"link_type"`
	LinkTo string `json:"link_to" db:"link_to"`
	ExternalLink string `json:"external_link" db:"external_link"`
}
