// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Web Form Field is the type-safe Go struct generated from the Web Form Field GoType.
type Web Form Field struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Fieldname string `json:"fieldname" db:"fieldname"`
	Fieldtype string `json:"fieldtype" db:"fieldtype"`
	Label string `json:"label" db:"label"`
	AllowReadOnAllLinkOptions int `json:"allow_read_on_all_link_options" db:"allow_read_on_all_link_options"`
	Reqd int `json:"reqd" db:"reqd"`
	DependsOn string `json:"depends_on" db:"depends_on"`
	ReadOnly int `json:"read_only" db:"read_only"`
	ShowInFilter int `json:"show_in_filter" db:"show_in_filter"`
	Hidden int `json:"hidden" db:"hidden"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	Options string `json:"options" db:"options"`
	MaxLength int `json:"max_length" db:"max_length"`
	MaxValue int `json:"max_value" db:"max_value"`
	SectionBreak6 string `json:"section_break_6" db:"section_break_6"`
	Description string `json:"description" db:"description"`
	ColumnBreak8 string `json:"column_break_8" db:"column_break_8"`
	Default string `json:"default" db:"default"`
	PropertyDependsOnSection string `json:"property_depends_on_section" db:"property_depends_on_section"`
	MandatoryDependsOn string `json:"mandatory_depends_on" db:"mandatory_depends_on"`
	ColumnBreak16 string `json:"column_break_16" db:"column_break_16"`
	ReadOnlyDependsOn string `json:"read_only_depends_on" db:"read_only_depends_on"`
	Precision string `json:"precision" db:"precision"`
	Placeholder string `json:"placeholder" db:"placeholder"`
}
