// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Onboarding Step is the type-safe Go struct generated from the Onboarding Step GoType.
type Onboarding Step struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	IsComplete int `json:"is_complete" db:"is_complete"`
	Title string `json:"title" db:"title"`
	ColumnBreak2 string `json:"column_break_2" db:"column_break_2"`
	SectionBreak5 string `json:"section_break_5" db:"section_break_5"`
	Action string `json:"action" db:"action"`
	ColumnBreak7 string `json:"column_break_7" db:"column_break_7"`
	ReferenceDocument string `json:"reference_document" db:"reference_document"`
	ReferenceReport string `json:"reference_report" db:"reference_report"`
	VideoUrl string `json:"video_url" db:"video_url"`
	ReportType string `json:"report_type" db:"report_type"`
	IsSkipped int `json:"is_skipped" db:"is_skipped"`
	Field string `json:"field" db:"field"`
	ValueToValidate string `json:"value_to_validate" db:"value_to_validate"`
	ReportDescription string `json:"report_description" db:"report_description"`
	ReportReferenceDoctype string `json:"report_reference_doctype" db:"report_reference_doctype"`
	IsSingle int `json:"is_single" db:"is_single"`
	Path string `json:"path" db:"path"`
	CallbackTitle string `json:"callback_title" db:"callback_title"`
	CallbackMessage string `json:"callback_message" db:"callback_message"`
	ValidateAction int `json:"validate_action" db:"validate_action"`
	ShowFullForm int `json:"show_full_form" db:"show_full_form"`
	DescriptionSection string `json:"description_section" db:"description_section"`
	Description string `json:"description" db:"description"`
	IntroVideoUrl string `json:"intro_video_url" db:"intro_video_url"`
	ActionLabel string `json:"action_label" db:"action_label"`
	ShowFormTour int `json:"show_form_tour" db:"show_form_tour"`
	FormTour string `json:"form_tour" db:"form_tour"`
	SectionBreakAjog string `json:"section_break_ajog" db:"section_break_ajog"`
	RouteOptions string `json:"route_options" db:"route_options"`
}
