// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Server Script is the type-safe Go struct generated from the Server Script GoType.
type Server Script struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ScriptType string `json:"script_type" db:"script_type"`
	Script string `json:"script" db:"script"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	DoctypeEvent string `json:"doctype_event" db:"doctype_event"`
	ApiMethod string `json:"api_method" db:"api_method"`
	AllowGuest int `json:"allow_guest" db:"allow_guest"`
	Disabled int `json:"disabled" db:"disabled"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	SectionBreak8 string `json:"section_break_8" db:"section_break_8"`
	HelpSection string `json:"help_section" db:"help_section"`
	HelpHtml string `json:"help_html" db:"help_html"`
	EventFrequency string `json:"event_frequency" db:"event_frequency"`
	Module string `json:"module" db:"module"`
	RateLimitingSection string `json:"rate_limiting_section" db:"rate_limiting_section"`
	EnableRateLimit int `json:"enable_rate_limit" db:"enable_rate_limit"`
	RateLimitCount int `json:"rate_limit_count" db:"rate_limit_count"`
	RateLimitSeconds int `json:"rate_limit_seconds" db:"rate_limit_seconds"`
	CronFormat string `json:"cron_format" db:"cron_format"`
}
