// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// EmailQueue is the type-safe Go struct generated from the EmailQueue GoType.
type EmailQueue struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Sender string `json:"sender" db:"sender"`
	Recipient string `json:"recipient" db:"recipient"`
	Message string `json:"message" db:"message"`
	Status string `json:"status" db:"status"`
	Error string `json:"error" db:"error"`
	Retry int `json:"retry" db:"retry"`
	EmailAccount string `json:"email_account" db:"email_account"`
}
