// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Email Queue is the type-safe Go struct generated from the Email Queue GoType.
type Email Queue struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Sender string `json:"sender" db:"sender"`
	Recipients string `json:"recipients" db:"recipients"`
	ShowAsCc string `json:"show_as_cc" db:"show_as_cc"`
	Message string `json:"message" db:"message"`
	Status string `json:"status" db:"status"`
	Error string `json:"error" db:"error"`
	MessageId string `json:"message_id" db:"message_id"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceName string `json:"reference_name" db:"reference_name"`
	Communication string `json:"communication" db:"communication"`
	SendAfter string `json:"send_after" db:"send_after"`
	Priority int `json:"priority" db:"priority"`
	AddUnsubscribeLink int `json:"add_unsubscribe_link" db:"add_unsubscribe_link"`
	UnsubscribeMethod string `json:"unsubscribe_method" db:"unsubscribe_method"`
	ExposeRecipients string `json:"expose_recipients" db:"expose_recipients"`
	Attachments string `json:"attachments" db:"attachments"`
	Retry int `json:"retry" db:"retry"`
	EmailAccount string `json:"email_account" db:"email_account"`
	UnsubscribeParams string `json:"unsubscribe_params" db:"unsubscribe_params"`
	RawHtml int `json:"raw_html" db:"raw_html"`
	RedactMessageAfterSend int `json:"redact_message_after_send" db:"redact_message_after_send"`
}
