// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Report is the type-safe Go struct generated from the Report GoType.
type Report struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ReportName string `json:"report_name" db:"report_name"`
	RefDoctype string `json:"ref_doctype" db:"ref_doctype"`
	ReferenceReport string `json:"reference_report" db:"reference_report"`
	IsStandard string `json:"is_standard" db:"is_standard"`
	Module string `json:"module" db:"module"`
	AddTotalRow int `json:"add_total_row" db:"add_total_row"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	ReportType string `json:"report_type" db:"report_type"`
	Disabled int `json:"disabled" db:"disabled"`
	LetterHead string `json:"letter_head" db:"letter_head"`
	SectionBreak6 string `json:"section_break_6" db:"section_break_6"`
	Query string `json:"query" db:"query"`
	Javascript string `json:"javascript" db:"javascript"`
	Json string `json:"json" db:"json"`
	PermissionRules string `json:"permission_rules" db:"permission_rules"`
	Roles string `json:"roles" db:"roles"`
	PreparedReport int `json:"prepared_report" db:"prepared_report"`
	ReportScript string `json:"report_script" db:"report_script"`
	FiltersSection string `json:"filters_section" db:"filters_section"`
	Filters string `json:"filters" db:"filters"`
	ColumnsSection string `json:"columns_section" db:"columns_section"`
	Columns string `json:"columns" db:"columns"`
	ClientCodeSection string `json:"client_code_section" db:"client_code_section"`
	Timeout int `json:"timeout" db:"timeout"`
	AddTranslateData int `json:"add_translate_data" db:"add_translate_data"`
	DisablePreparedReportAutomation int `json:"disable_prepared_report_automation" db:"disable_prepared_report_automation"`
	SectionBreakTljw string `json:"section_break_tljw" db:"section_break_tljw"`
	DoctypeToSync string `json:"doctype_to_sync" db:"doctype_to_sync"`
	SnapshotReport int `json:"snapshot_report" db:"snapshot_report"`
}
