// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Package Release is the type-safe Go struct generated from the Package Release GoType.
type Package Release struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Package string `json:"package" db:"package"`
	Major int `json:"major" db:"major"`
	Minor int `json:"minor" db:"minor"`
	Patch int `json:"patch" db:"patch"`
	Path string `json:"path" db:"path"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	SectionBreak7 string `json:"section_break_7" db:"section_break_7"`
	ReleaseNotes string `json:"release_notes" db:"release_notes"`
	Publish int `json:"publish" db:"publish"`
}
