// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Web Template Field is the type-safe Go struct generated from the Web Template Field GoType.
type Web Template Field struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Label string `json:"label" db:"label"`
	Fieldname string `json:"fieldname" db:"fieldname"`
	Fieldtype string `json:"fieldtype" db:"fieldtype"`
	Reqd int `json:"reqd" db:"reqd"`
	Options string `json:"options" db:"options"`
	Default string `json:"default" db:"default"`
}
