// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Web Page Block is the type-safe Go struct generated from the Web Page Block GoType.
type Web Page Block struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	WebTemplate string `json:"web_template" db:"web_template"`
	EditValues string `json:"edit_values" db:"edit_values"`
	WebTemplateValues string `json:"web_template_values" db:"web_template_values"`
	CssClass string `json:"css_class" db:"css_class"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	AddShade int `json:"add_shade" db:"add_shade"`
	AddContainer int `json:"add_container" db:"add_container"`
	HideBlock int `json:"hide_block" db:"hide_block"`
	AddTopPadding int `json:"add_top_padding" db:"add_top_padding"`
	AddBottomPadding int `json:"add_bottom_padding" db:"add_bottom_padding"`
	AddBorderAtTop int `json:"add_border_at_top" db:"add_border_at_top"`
	AddBorderAtBottom int `json:"add_border_at_bottom" db:"add_border_at_bottom"`
	AddBackgroundImage int `json:"add_background_image" db:"add_background_image"`
	BackgroundImage string `json:"background_image" db:"background_image"`
	SectionId string `json:"section_id" db:"section_id"`
}
