// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DuckDB Sync is the type-safe Go struct generated from the DuckDB Sync GoType.
type DuckDB Sync struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DbTables string `json:"db_tables" db:"db_tables"`
	DocType string `json:"doc_type" db:"doc_type"`
	AmendedFrom string `json:"amended_from" db:"amended_from"`
	ColumnBreakMylv string `json:"column_break_mylv" db:"column_break_mylv"`
	Filename string `json:"filename" db:"filename"`
	SectionBreakOhzq string `json:"section_break_ohzq" db:"section_break_ohzq"`
}
