// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Connected App is the type-safe Go struct generated from the Connected App GoType.
type Connected App struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ProviderName string `json:"provider_name" db:"provider_name"`
	Cb00 string `json:"cb_00" db:"cb_00"`
	OpenidConfiguration string `json:"openid_configuration" db:"openid_configuration"`
	SbClientCredentialsSection string `json:"sb_client_credentials_section" db:"sb_client_credentials_section"`
	ClientId string `json:"client_id" db:"client_id"`
	RedirectUri string `json:"redirect_uri" db:"redirect_uri"`
	Cb01 string `json:"cb_01" db:"cb_01"`
	ClientSecret string `json:"client_secret" db:"client_secret"`
	SbScopeSection string `json:"sb_scope_section" db:"sb_scope_section"`
	SbEndpointsSection string `json:"sb_endpoints_section" db:"sb_endpoints_section"`
	Cb02 string `json:"cb_02" db:"cb_02"`
	Scopes string `json:"scopes" db:"scopes"`
	AuthorizationUri string `json:"authorization_uri" db:"authorization_uri"`
	TokenUri string `json:"token_uri" db:"token_uri"`
	RevocationUri string `json:"revocation_uri" db:"revocation_uri"`
	UserinfoUri string `json:"userinfo_uri" db:"userinfo_uri"`
	IntrospectionUri string `json:"introspection_uri" db:"introspection_uri"`
	SectionBreak18 string `json:"section_break_18" db:"section_break_18"`
	QueryParameters string `json:"query_parameters" db:"query_parameters"`
}
