// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Domain Settings is the type-safe Go struct generated from the Domain Settings GoType.
type Domain Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ActiveDomainsSb string `json:"active_domains_sb" db:"active_domains_sb"`
	DomainsHtml string `json:"domains_html" db:"domains_html"`
	ActiveDomains string `json:"active_domains" db:"active_domains"`
}
