// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// LDAP Settings is the type-safe Go struct generated from the LDAP Settings GoType.
type LDAP Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Enabled int `json:"enabled" db:"enabled"`
	LdapServerUrl string `json:"ldap_server_url" db:"ldap_server_url"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	BaseDn string `json:"base_dn" db:"base_dn"`
	Password string `json:"password" db:"password"`
	DefaultRole string `json:"default_role" db:"default_role"`
	LdapSearchString string `json:"ldap_search_string" db:"ldap_search_string"`
	LdapEmailField string `json:"ldap_email_field" db:"ldap_email_field"`
	LdapUsernameField string `json:"ldap_username_field" db:"ldap_username_field"`
	LdapFirstNameField string `json:"ldap_first_name_field" db:"ldap_first_name_field"`
	LdapMiddleNameField string `json:"ldap_middle_name_field" db:"ldap_middle_name_field"`
	LdapLastNameField string `json:"ldap_last_name_field" db:"ldap_last_name_field"`
	LdapPhoneField string `json:"ldap_phone_field" db:"ldap_phone_field"`
	LdapMobileField string `json:"ldap_mobile_field" db:"ldap_mobile_field"`
	LdapSecurity string `json:"ldap_security" db:"ldap_security"`
	SslTlsMode string `json:"ssl_tls_mode" db:"ssl_tls_mode"`
	RequireTrustedCertificate string `json:"require_trusted_certificate" db:"require_trusted_certificate"`
	LocalPrivateKeyFile string `json:"local_private_key_file" db:"local_private_key_file"`
	LocalServerCertificateFile string `json:"local_server_certificate_file" db:"local_server_certificate_file"`
	LocalCaCertsFile string `json:"local_ca_certs_file" db:"local_ca_certs_file"`
	LdapGroupMappingsSection string `json:"ldap_group_mappings_section" db:"ldap_group_mappings_section"`
	LdapGroupField string `json:"ldap_group_field" db:"ldap_group_field"`
	LdapGroups string `json:"ldap_groups" db:"ldap_groups"`
	LdapServerSettingsSection string `json:"ldap_server_settings_section" db:"ldap_server_settings_section"`
	LdapAuthSection string `json:"ldap_auth_section" db:"ldap_auth_section"`
	ColumnBreak8 string `json:"column_break_8" db:"column_break_8"`
	LdapSearchAndPathsSection string `json:"ldap_search_and_paths_section" db:"ldap_search_and_paths_section"`
	ColumnBreak12 string `json:"column_break_12" db:"column_break_12"`
	LdapUserCreationAndMappingSection string `json:"ldap_user_creation_and_mapping_section" db:"ldap_user_creation_and_mapping_section"`
	ColumnBreak19 string `json:"column_break_19" db:"column_break_19"`
	ColumnBreak27 string `json:"column_break_27" db:"column_break_27"`
	LdapCustomSettingsSection string `json:"ldap_custom_settings_section" db:"ldap_custom_settings_section"`
	ColumnBreak33 string `json:"column_break_33" db:"column_break_33"`
	LdapGroupMemberAttribute string `json:"ldap_group_member_attribute" db:"ldap_group_member_attribute"`
	LdapDirectoryServer string `json:"ldap_directory_server" db:"ldap_directory_server"`
	LdapGroupObjectclass string `json:"ldap_group_objectclass" db:"ldap_group_objectclass"`
	LdapCustomGroupSearch string `json:"ldap_custom_group_search" db:"ldap_custom_group_search"`
	LdapSearchPathUser string `json:"ldap_search_path_user" db:"ldap_search_path_user"`
	LdapSearchPathGroup string `json:"ldap_search_path_group" db:"ldap_search_path_group"`
	DefaultUserType string `json:"default_user_type" db:"default_user_type"`
	ColumnBreak38 string `json:"column_break_38" db:"column_break_38"`
	SectionBreak40 string `json:"section_break_40" db:"section_break_40"`
	DoNotCreateNewUser int `json:"do_not_create_new_user" db:"do_not_create_new_user"`
}
