// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Dashboard Chart Link is the type-safe Go struct generated from the Dashboard Chart Link GoType.
type Dashboard Chart Link struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Chart string `json:"chart" db:"chart"`
	Width string `json:"width" db:"width"`
}
