// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workflow Action Master is the type-safe Go struct generated from the Workflow Action Master GoType.
type Workflow Action Master struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	WorkflowActionName string `json:"workflow_action_name" db:"workflow_action_name"`
}
