// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Workflow Transition Tasks is the type-safe Go struct generated from the Workflow Transition Tasks GoType.
type Workflow Transition Tasks struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Tasks string `json:"tasks" db:"tasks"`
}
