// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Portal Menu Item is the type-safe Go struct generated from the Portal Menu Item GoType.
type Portal Menu Item struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	Enabled int `json:"enabled" db:"enabled"`
	Route string `json:"route" db:"route"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	Role string `json:"role" db:"role"`
	Target string `json:"target" db:"target"`
}
