// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// ModuleDef is the type-safe Go struct generated from the ModuleDef GoType.
type ModuleDef struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ModuleName string `json:"module_name" db:"module_name"`
	AppName string `json:"app_name" db:"app_name"`
	Custom int `json:"custom" db:"custom"`
	Disabled int `json:"disabled" db:"disabled"`
}
