// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Module Def is the type-safe Go struct generated from the Module Def GoType.
type Module Def struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ModuleName string `json:"module_name" db:"module_name"`
	AppName string `json:"app_name" db:"app_name"`
	RestrictToDomain string `json:"restrict_to_domain" db:"restrict_to_domain"`
	Custom int `json:"custom" db:"custom"`
	Package string `json:"package" db:"package"`
	ConnectionsTab string `json:"connections_tab" db:"connections_tab"`
	DetailsTab string `json:"details_tab" db:"details_tab"`
	ColumnBreakGiia string `json:"column_break_giia" db:"column_break_giia"`
	SectionBreakDnma string `json:"section_break_dnma" db:"section_break_dnma"`
}
