// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Sidebar Item Group is the type-safe Go struct generated from the Sidebar Item Group GoType.
type Sidebar Item Group struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Sidebar string `json:"sidebar" db:"sidebar"`
	Links string `json:"links" db:"links"`
	App string `json:"app" db:"app"`
}
