// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// User Permission is the type-safe Go struct generated from the User Permission GoType.
type User Permission struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	User string `json:"user" db:"user"`
	Allow string `json:"allow" db:"allow"`
	ForValue string `json:"for_value" db:"for_value"`
	IsDefault int `json:"is_default" db:"is_default"`
	AdvancedControlSection string `json:"advanced_control_section" db:"advanced_control_section"`
	ApplyToAllDoctypes int `json:"apply_to_all_doctypes" db:"apply_to_all_doctypes"`
	ApplicableFor string `json:"applicable_for" db:"applicable_for"`
	ColumnBreak9 string `json:"column_break_9" db:"column_break_9"`
	HideDescendants int `json:"hide_descendants" db:"hide_descendants"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
}
