// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Website Route Redirect is the type-safe Go struct generated from the Website Route Redirect GoType.
type Website Route Redirect struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Source string `json:"source" db:"source"`
	Target string `json:"target" db:"target"`
	RedirectHttpStatus string `json:"redirect_http_status" db:"redirect_http_status"`
	ColumnBreakMzuh string `json:"column_break_mzuh" db:"column_break_mzuh"`
	ForwardQueryParameters int `json:"forward_query_parameters" db:"forward_query_parameters"`
}
