// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DocField is the type-safe Go struct generated from the DocField GoType.
type DocField struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Fieldname string `json:"fieldname" db:"fieldname"`
	Fieldtype string `json:"fieldtype" db:"fieldtype"`
	Label string `json:"label" db:"label"`
	Reqd int `json:"reqd" db:"reqd"`
	Options string `json:"options" db:"options"`
	Default string `json:"default" db:"default"`
	Description string `json:"description" db:"description"`
	Hidden int `json:"hidden" db:"hidden"`
	ReadOnly int `json:"read_only" db:"read_only"`
}
