// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Token Cache is the type-safe Go struct generated from the Token Cache GoType.
type Token Cache struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	User string `json:"user" db:"user"`
	ConnectedApp string `json:"connected_app" db:"connected_app"`
	AccessToken string `json:"access_token" db:"access_token"`
	RefreshToken string `json:"refresh_token" db:"refresh_token"`
	ExpiresIn int `json:"expires_in" db:"expires_in"`
	State string `json:"state" db:"state"`
	Scopes string `json:"scopes" db:"scopes"`
	SuccessUri string `json:"success_uri" db:"success_uri"`
	TokenType string `json:"token_type" db:"token_type"`
	ProviderName string `json:"provider_name" db:"provider_name"`
}
