// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DocPerm is the type-safe Go struct generated from the DocPerm GoType.
type DocPerm struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Role string `json:"role" db:"role"`
	Read int `json:"read" db:"read"`
	Write int `json:"write" db:"write"`
	Create int `json:"create" db:"create"`
	Delete int `json:"delete" db:"delete"`
	Submit int `json:"submit" db:"submit"`
	Cancel int `json:"cancel" db:"cancel"`
}
