// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Activity Log is the type-safe Go struct generated from the Activity Log GoType.
type Activity Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Subject string `json:"subject" db:"subject"`
	SectionBreak8 string `json:"section_break_8" db:"section_break_8"`
	Content string `json:"content" db:"content"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	AdditionalInfo string `json:"additional_info" db:"additional_info"`
	CommunicationDate string `json:"communication_date" db:"communication_date"`
	ColumnBreak7 string `json:"column_break_7" db:"column_break_7"`
	Operation string `json:"operation" db:"operation"`
	Status string `json:"status" db:"status"`
	ReferenceSection string `json:"reference_section" db:"reference_section"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceName string `json:"reference_name" db:"reference_name"`
	ReferenceOwner string `json:"reference_owner" db:"reference_owner"`
	ColumnBreak14 string `json:"column_break_14" db:"column_break_14"`
	TimelineDoctype string `json:"timeline_doctype" db:"timeline_doctype"`
	TimelineName string `json:"timeline_name" db:"timeline_name"`
	LinkDoctype string `json:"link_doctype" db:"link_doctype"`
	LinkName string `json:"link_name" db:"link_name"`
	User string `json:"user" db:"user"`
	FullName string `json:"full_name" db:"full_name"`
	IpAddress string `json:"ip_address" db:"ip_address"`
}
