// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// ActivityLog is the type-safe Go struct generated from the ActivityLog GoType.
type ActivityLog struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	User string `json:"user" db:"user"`
	Operation string `json:"operation" db:"operation"`
	Subject string `json:"subject" db:"subject"`
	Status string `json:"status" db:"status"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceName string `json:"reference_name" db:"reference_name"`
	IpAddress string `json:"ip_address" db:"ip_address"`
}
