// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Prepared Report is the type-safe Go struct generated from the Prepared Report GoType.
type Prepared Report struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ReportName string `json:"report_name" db:"report_name"`
	Status string `json:"status" db:"status"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	ReportEndTime string `json:"report_end_time" db:"report_end_time"`
	SectionBreak7 string `json:"section_break_7" db:"section_break_7"`
	ErrorMessage string `json:"error_message" db:"error_message"`
	FiltersSb string `json:"filters_sb" db:"filters_sb"`
	Filters string `json:"filters" db:"filters"`
	FilterValues string `json:"filter_values" db:"filter_values"`
	JobId string `json:"job_id" db:"job_id"`
	QueuedBy string `json:"queued_by" db:"queued_by"`
	QueuedAt string `json:"queued_at" db:"queued_at"`
	PeakMemoryUsage int `json:"peak_memory_usage" db:"peak_memory_usage"`
}
