// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Doctype To Sync is the type-safe Go struct generated from the Doctype To Sync GoType.
type Doctype To Sync struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DocType string `json:"doc_type" db:"doc_type"`
}
