// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Notification Log is the type-safe Go struct generated from the Notification Log GoType.
type Notification Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	NotificationSection string `json:"notification_section" db:"notification_section"`
	Type string `json:"type" db:"type"`
	Title string `json:"title" db:"title"`
	Description string `json:"description" db:"description"`
	ReferenceSection string `json:"reference_section" db:"reference_section"`
	DocumentType string `json:"document_type" db:"document_type"`
	DocumentName string `json:"document_name" db:"document_name"`
	SourceDoctype string `json:"source_doctype" db:"source_doctype"`
	SourceName string `json:"source_name" db:"source_name"`
	App string `json:"app" db:"app"`
	ColumnBreakRef string `json:"column_break_ref" db:"column_break_ref"`
	Link string `json:"link" db:"link"`
	OpenReferenceDocument string `json:"open_reference_document" db:"open_reference_document"`
	RecipientSection string `json:"recipient_section" db:"recipient_section"`
	ForUser string `json:"for_user" db:"for_user"`
	FromUser string `json:"from_user" db:"from_user"`
	ColumnBreakRec string `json:"column_break_rec" db:"column_break_rec"`
	Read int `json:"read" db:"read"`
	AttachmentSection string `json:"attachment_section" db:"attachment_section"`
	AttachedFile string `json:"attached_file" db:"attached_file"`
	AttachmentLink string `json:"attachment_link" db:"attachment_link"`
	EmailSection string `json:"email_section" db:"email_section"`
	Subject string `json:"subject" db:"subject"`
	EmailContent string `json:"email_content" db:"email_content"`
	EmailHeader string `json:"email_header" db:"email_header"`
}
