// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// User Type is the type-safe Go struct generated from the User Type GoType.
type User Type struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	IsStandard int `json:"is_standard" db:"is_standard"`
	SectionBreak2 string `json:"section_break_2" db:"section_break_2"`
	UserDoctypes string `json:"user_doctypes" db:"user_doctypes"`
	Role string `json:"role" db:"role"`
	SelectDoctypes string `json:"select_doctypes" db:"select_doctypes"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	ApplyUserPermissionOn string `json:"apply_user_permission_on" db:"apply_user_permission_on"`
	SectionBreak6 string `json:"section_break_6" db:"section_break_6"`
	UserIdField string `json:"user_id_field" db:"user_id_field"`
	AllowedModulesSection string `json:"allowed_modules_section" db:"allowed_modules_section"`
	UserTypeModules string `json:"user_type_modules" db:"user_type_modules"`
	CustomSelectDoctypes string `json:"custom_select_doctypes" db:"custom_select_doctypes"`
}
