// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Patch Log is the type-safe Go struct generated from the Patch Log GoType.
type Patch Log struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Patch string `json:"patch" db:"patch"`
	Skipped int `json:"skipped" db:"skipped"`
	Traceback string `json:"traceback" db:"traceback"`
}
