// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Client Script is the type-safe Go struct generated from the Client Script GoType.
type Client Script struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Dt string `json:"dt" db:"dt"`
	Script string `json:"script" db:"script"`
	Sample string `json:"sample" db:"sample"`
	Enabled int `json:"enabled" db:"enabled"`
	View string `json:"view" db:"view"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	Module string `json:"module" db:"module"`
	SectionBreak6 string `json:"section_break_6" db:"section_break_6"`
}
