// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Dashboard is the type-safe Go struct generated from the Dashboard GoType.
type Dashboard struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DashboardName string `json:"dashboard_name" db:"dashboard_name"`
	IsDefault int `json:"is_default" db:"is_default"`
	Charts string `json:"charts" db:"charts"`
	ChartOptions string `json:"chart_options" db:"chart_options"`
	Cards string `json:"cards" db:"cards"`
	IsStandard int `json:"is_standard" db:"is_standard"`
	Module string `json:"module" db:"module"`
}
