// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Web Page View is the type-safe Go struct generated from the Web Page View GoType.
type Web Page View struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Path string `json:"path" db:"path"`
	Referrer string `json:"referrer" db:"referrer"`
	Browser string `json:"browser" db:"browser"`
	BrowserVersion string `json:"browser_version" db:"browser_version"`
	IsUnique string `json:"is_unique" db:"is_unique"`
	TimeZone string `json:"time_zone" db:"time_zone"`
	UserAgent string `json:"user_agent" db:"user_agent"`
	VisitorId string `json:"visitor_id" db:"visitor_id"`
	Source string `json:"source" db:"source"`
	Campaign string `json:"campaign" db:"campaign"`
	Medium string `json:"medium" db:"medium"`
	Content string `json:"content" db:"content"`
}
