// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Navbar Item is the type-safe Go struct generated from the Navbar Item GoType.
type Navbar Item struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ItemLabel string `json:"item_label" db:"item_label"`
	ItemType string `json:"item_type" db:"item_type"`
	Hidden int `json:"hidden" db:"hidden"`
	IsStandard int `json:"is_standard" db:"is_standard"`
	Route string `json:"route" db:"route"`
	Action string `json:"action" db:"action"`
	Condition string `json:"condition" db:"condition"`
	ColumnBreakDtwu string `json:"column_break_dtwu" db:"column_break_dtwu"`
	Icon string `json:"icon" db:"icon"`
}
