// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Website Settings is the type-safe Go struct generated from the Website Settings GoType.
type Website Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Sb0 string `json:"sb0" db:"sb0"`
	HomePage string `json:"home_page" db:"home_page"`
	Cb4 string `json:"cb4" db:"cb4"`
	TitlePrefix string `json:"title_prefix" db:"title_prefix"`
	SectionBreak6 string `json:"section_break_6" db:"section_break_6"`
	WebsiteTheme string `json:"website_theme" db:"website_theme"`
	WebsiteThemeImage string `json:"website_theme_image" db:"website_theme_image"`
	WebsiteThemeImageLink string `json:"website_theme_image_link" db:"website_theme_image_link"`
	Brand string `json:"brand" db:"brand"`
	BannerImage string `json:"banner_image" db:"banner_image"`
	BrandHtml string `json:"brand_html" db:"brand_html"`
	SetBannerFromImage string `json:"set_banner_from_image" db:"set_banner_from_image"`
	TopBar string `json:"top_bar" db:"top_bar"`
	NavbarSearch int `json:"navbar_search" db:"navbar_search"`
	TopBarItems string `json:"top_bar_items" db:"top_bar_items"`
	Banner string `json:"banner" db:"banner"`
	BannerHtml string `json:"banner_html" db:"banner_html"`
	Footer string `json:"footer" db:"footer"`
	Copyright string `json:"copyright" db:"copyright"`
	Address string `json:"address" db:"address"`
	FooterItems string `json:"footer_items" db:"footer_items"`
	HideFooterSignup int `json:"hide_footer_signup" db:"hide_footer_signup"`
	Integrations string `json:"integrations" db:"integrations"`
	GoogleAnalyticsId string `json:"google_analytics_id" db:"google_analytics_id"`
	ColumnBreak17 string `json:"column_break_17" db:"column_break_17"`
	MiscSection string `json:"misc_section" db:"misc_section"`
	Favicon string `json:"favicon" db:"favicon"`
	Subdomain string `json:"subdomain" db:"subdomain"`
	DisableSignup int `json:"disable_signup" db:"disable_signup"`
	SectionBreak38 string `json:"section_break_38" db:"section_break_38"`
	HeadHtml string `json:"head_html" db:"head_html"`
	RobotsTxt string `json:"robots_txt" db:"robots_txt"`
	RouteRedirects string `json:"route_redirects" db:"route_redirects"`
	EnableGoogleIndexing int `json:"enable_google_indexing" db:"enable_google_indexing"`
	IndexingRefreshToken string `json:"indexing_refresh_token" db:"indexing_refresh_token"`
	IndexingAuthorizationCode string `json:"indexing_authorization_code" db:"indexing_authorization_code"`
	AuthorizeApiIndexingAccess string `json:"authorize_api_indexing_access" db:"authorize_api_indexing_access"`
	EnableViewTracking int `json:"enable_view_tracking" db:"enable_view_tracking"`
	FooterLogo string `json:"footer_logo" db:"footer_logo"`
	CallToAction string `json:"call_to_action" db:"call_to_action"`
	CallToActionUrl string `json:"call_to_action_url" db:"call_to_action_url"`
	HideLogin int `json:"hide_login" db:"hide_login"`
	NavbarTemplate string `json:"navbar_template" db:"navbar_template"`
	NavbarTemplateValues string `json:"navbar_template_values" db:"navbar_template_values"`
	EditNavbarTemplateValues string `json:"edit_navbar_template_values" db:"edit_navbar_template_values"`
	FooterTemplate string `json:"footer_template" db:"footer_template"`
	FooterTemplateValues string `json:"footer_template_values" db:"footer_template_values"`
	EditFooterTemplateValues string `json:"edit_footer_template_values" db:"edit_footer_template_values"`
	GoogleAnalyticsAnonymizeIp int `json:"google_analytics_anonymize_ip" db:"google_analytics_anonymize_ip"`
	ShowLanguagePicker int `json:"show_language_picker" db:"show_language_picker"`
	NavbarTemplateSection string `json:"navbar_template_section" db:"navbar_template_section"`
	AppName string `json:"app_name" db:"app_name"`
	AppLogo string `json:"app_logo" db:"app_logo"`
	AccountDeletionSettingsSection string `json:"account_deletion_settings_section" db:"account_deletion_settings_section"`
	ShowAccountDeletionLink int `json:"show_account_deletion_link" db:"show_account_deletion_link"`
	AutoAccountDeletion int `json:"auto_account_deletion" db:"auto_account_deletion"`
	FooterPowered string `json:"footer_powered" db:"footer_powered"`
	SplashImage string `json:"splash_image" db:"splash_image"`
	HomeTab string `json:"home_tab" db:"home_tab"`
	NavbarTab string `json:"navbar_tab" db:"navbar_tab"`
	FooterTab string `json:"footer_tab" db:"footer_tab"`
	FooterDetailsSection string `json:"footer_details_section" db:"footer_details_section"`
	ColumnBreak37 string `json:"column_break_37" db:"column_break_37"`
	CustomFooterSection string `json:"custom_footer_section" db:"custom_footer_section"`
	RedirectsTab string `json:"redirects_tab" db:"redirects_tab"`
	ColumnBreak9 string `json:"column_break_9" db:"column_break_9"`
	AnalyticsSection string `json:"analytics_section" db:"analytics_section"`
	ShowFooterOnLogin int `json:"show_footer_on_login" db:"show_footer_on_login"`
}
