// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Notification Type is the type-safe Go struct generated from the Notification Type GoType.
type Notification Type struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	TypeName string `json:"type_name" db:"type_name"`
	Enabled int `json:"enabled" db:"enabled"`
}
