// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Assignment Rule User is the type-safe Go struct generated from the Assignment Rule User GoType.
type Assignment Rule User struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	User string `json:"user" db:"user"`
	Weight int `json:"weight" db:"weight"`
}
