// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Kanban Board Column is the type-safe Go struct generated from the Kanban Board Column GoType.
type Kanban Board Column struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ColumnName string `json:"column_name" db:"column_name"`
	Status string `json:"status" db:"status"`
	Indicator string `json:"indicator" db:"indicator"`
	Order string `json:"order" db:"order"`
}
