// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Address is the type-safe Go struct generated from the Address GoType.
type Address struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	AddressTitle string `json:"address_title" db:"address_title"`
	AddressType string `json:"address_type" db:"address_type"`
	AddressLine1 string `json:"address_line1" db:"address_line1"`
	AddressLine2 string `json:"address_line2" db:"address_line2"`
	City string `json:"city" db:"city"`
	State string `json:"state" db:"state"`
	Country string `json:"country" db:"country"`
	Pincode string `json:"pincode" db:"pincode"`
	EmailId string `json:"email_id" db:"email_id"`
	Phone string `json:"phone" db:"phone"`
	IsPrimaryAddress int `json:"is_primary_address" db:"is_primary_address"`
	IsShippingAddress int `json:"is_shipping_address" db:"is_shipping_address"`
	Disabled int `json:"disabled" db:"disabled"`
}
