// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Translation is the type-safe Go struct generated from the Translation GoType.
type Translation struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Language string `json:"language" db:"language"`
	SectionBreak4 string `json:"section_break_4" db:"section_break_4"`
	ColumnBreak6 string `json:"column_break_6" db:"column_break_6"`
	SectionBreak6 string `json:"section_break_6" db:"section_break_6"`
	Context string `json:"context" db:"context"`
	Contributed int `json:"contributed" db:"contributed"`
	ContributionStatus string `json:"contribution_status" db:"contribution_status"`
	ContributionDocname string `json:"contribution_docname" db:"contribution_docname"`
	SourceText string `json:"source_text" db:"source_text"`
	TranslatedText string `json:"translated_text" db:"translated_text"`
}
