// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Dashboard Settings is the type-safe Go struct generated from the Dashboard Settings GoType.
type Dashboard Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	User string `json:"user" db:"user"`
	ChartConfig string `json:"chart_config" db:"chart_config"`
}
