// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// OAuth Client is the type-safe Go struct generated from the OAuth Client GoType.
type OAuth Client struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ClientId string `json:"client_id" db:"client_id"`
	AppName string `json:"app_name" db:"app_name"`
	User string `json:"user" db:"user"`
	Cb1 string `json:"cb_1" db:"cb_1"`
	ClientSecret string `json:"client_secret" db:"client_secret"`
	SkipAuthorization int `json:"skip_authorization" db:"skip_authorization"`
	Scopes string `json:"scopes" db:"scopes"`
	RedirectUris string `json:"redirect_uris" db:"redirect_uris"`
	DefaultRedirectUri string `json:"default_redirect_uri" db:"default_redirect_uri"`
	SbAdvanced string `json:"sb_advanced" db:"sb_advanced"`
	GrantType string `json:"grant_type" db:"grant_type"`
	Cb2 string `json:"cb_2" db:"cb_2"`
	ResponseType string `json:"response_type" db:"response_type"`
	AllowedRoles string `json:"allowed_roles" db:"allowed_roles"`
	ClientMetadataSection string `json:"client_metadata_section" db:"client_metadata_section"`
	ClientUri string `json:"client_uri" db:"client_uri"`
	ColumnBreakHtfq string `json:"column_break_htfq" db:"column_break_htfq"`
	LogoUri string `json:"logo_uri" db:"logo_uri"`
	SectionBreakGgiv string `json:"section_break_ggiv" db:"section_break_ggiv"`
	SoftwareId string `json:"software_id" db:"software_id"`
	ColumnBreakZiii string `json:"column_break_ziii" db:"column_break_ziii"`
	SoftwareVersion string `json:"software_version" db:"software_version"`
	TosUri string `json:"tos_uri" db:"tos_uri"`
	PolicyUri string `json:"policy_uri" db:"policy_uri"`
	Contacts string `json:"contacts" db:"contacts"`
	TokenEndpointAuthMethod string `json:"token_endpoint_auth_method" db:"token_endpoint_auth_method"`
}
