// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Success Action is the type-safe Go struct generated from the Success Action GoType.
type Success Action struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	RefDoctype string `json:"ref_doctype" db:"ref_doctype"`
	FirstSuccessMessage string `json:"first_success_message" db:"first_success_message"`
	Message string `json:"message" db:"message"`
	NextActionsHtml string `json:"next_actions_html" db:"next_actions_html"`
	NextActions string `json:"next_actions" db:"next_actions"`
	ActionTimeout int `json:"action_timeout" db:"action_timeout"`
}
