// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Notification Settings is the type-safe Go struct generated from the Notification Settings GoType.
type Notification Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Enabled int `json:"enabled" db:"enabled"`
	SubscribedDocuments string `json:"subscribed_documents" db:"subscribed_documents"`
	ColumnBreak3 string `json:"column_break_3" db:"column_break_3"`
	EnableEmailNotifications int `json:"enable_email_notifications" db:"enable_email_notifications"`
	EmailNotificationTypes string `json:"email_notification_types" db:"email_notification_types"`
	EmailNotificationTypesHtml string `json:"email_notification_types_html" db:"email_notification_types_html"`
	EnableEmailMention int `json:"enable_email_mention" db:"enable_email_mention"`
	EnableEmailAssignment int `json:"enable_email_assignment" db:"enable_email_assignment"`
	EnableEmailShare int `json:"enable_email_share" db:"enable_email_share"`
	Seen int `json:"seen" db:"seen"`
	EnableEmailEventReminders int `json:"enable_email_event_reminders" db:"enable_email_event_reminders"`
	EnableEmailThreadsOnAssignedDocument int `json:"enable_email_threads_on_assigned_document" db:"enable_email_threads_on_assigned_document"`
}
