// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// System Health Report Errors is the type-safe Go struct generated from the System Health Report Errors GoType.
type System Health Report Errors struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Title string `json:"title" db:"title"`
	Occurrences int `json:"occurrences" db:"occurrences"`
}
