// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// System Health Report Queue is the type-safe Go struct generated from the System Health Report Queue GoType.
type System Health Report Queue struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Queue string `json:"queue" db:"queue"`
	PendingJobs int `json:"pending_jobs" db:"pending_jobs"`
}
