// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// About Us Settings is the type-safe Go struct generated from the About Us Settings GoType.
type About Us Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	CompanyIntroduction string `json:"company_introduction" db:"company_introduction"`
	Sb0 string `json:"sb0" db:"sb0"`
	CompanyHistoryHeading string `json:"company_history_heading" db:"company_history_heading"`
	CompanyHistory string `json:"company_history" db:"company_history"`
	Sb1 string `json:"sb1" db:"sb1"`
	TeamMembersHeading string `json:"team_members_heading" db:"team_members_heading"`
	TeamMembers string `json:"team_members" db:"team_members"`
	Footer string `json:"footer" db:"footer"`
	PageTitle string `json:"page_title" db:"page_title"`
	TeamMembersSubtitle string `json:"team_members_subtitle" db:"team_members_subtitle"`
	IsDisabled int `json:"is_disabled" db:"is_disabled"`
}
