// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// User Invitation is the type-safe Go struct generated from the User Invitation GoType.
type User Invitation struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Email string `json:"email" db:"email"`
	InvitedBy string `json:"invited_by" db:"invited_by"`
	Status string `json:"status" db:"status"`
	EmailSentAt string `json:"email_sent_at" db:"email_sent_at"`
	AcceptedAt string `json:"accepted_at" db:"accepted_at"`
	User string `json:"user" db:"user"`
	AppName string `json:"app_name" db:"app_name"`
	RedirectToPath string `json:"redirect_to_path" db:"redirect_to_path"`
	Key string `json:"key" db:"key"`
	Roles string `json:"roles" db:"roles"`
}
