// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Website Slideshow Item is the type-safe Go struct generated from the Website Slideshow Item GoType.
type Website Slideshow Item struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Image string `json:"image" db:"image"`
	Heading string `json:"heading" db:"heading"`
	Description string `json:"description" db:"description"`
	Url string `json:"url" db:"url"`
}
