// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// List View Settings is the type-safe Go struct generated from the List View Settings GoType.
type List View Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DisableCount int `json:"disable_count" db:"disable_count"`
	DisableSidebarStats int `json:"disable_sidebar_stats" db:"disable_sidebar_stats"`
	DisableAutoRefresh int `json:"disable_auto_refresh" db:"disable_auto_refresh"`
	FieldsHtml string `json:"fields_html" db:"fields_html"`
	Fields string `json:"fields" db:"fields"`
	DisableCommentCount int `json:"disable_comment_count" db:"disable_comment_count"`
	AllowEdit int `json:"allow_edit" db:"allow_edit"`
	DisableAutomaticRecencyFilters int `json:"disable_automatic_recency_filters" db:"disable_automatic_recency_filters"`
	DisableScrolling int `json:"disable_scrolling" db:"disable_scrolling"`
	ColumnBreakOany string `json:"column_break_oany" db:"column_break_oany"`
	SectionBreakEvqq string `json:"section_break_evqq" db:"section_break_evqq"`
	ShowTags int `json:"show_tags" db:"show_tags"`
}
