// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// User Role Profile is the type-safe Go struct generated from the User Role Profile GoType.
type User Role Profile struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	RoleProfile string `json:"role_profile" db:"role_profile"`
}
