// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Audit Trail is the type-safe Go struct generated from the Audit Trail GoType.
type Audit Trail struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	DoctypeName string `json:"doctype_name" db:"doctype_name"`
	Document string `json:"document" db:"document"`
	ColumnBreakPeck string `json:"column_break_peck" db:"column_break_peck"`
	SectionBreakGppi string `json:"section_break_gppi" db:"section_break_gppi"`
	VersionTable string `json:"version_table" db:"version_table"`
	RowsAdded string `json:"rows_added" db:"rows_added"`
	RowsRemoved string `json:"rows_removed" db:"rows_removed"`
	RowsAddedSection string `json:"rows_added_section" db:"rows_added_section"`
	RowsRemovedSection string `json:"rows_removed_section" db:"rows_removed_section"`
	StartDate string `json:"start_date" db:"start_date"`
	EndDate string `json:"end_date" db:"end_date"`
	SectionBreakDfrx string `json:"section_break_dfrx" db:"section_break_dfrx"`
	ColumnBreakYtzm string `json:"column_break_ytzm" db:"column_break_ytzm"`
}
