// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Network Printer Settings is the type-safe Go struct generated from the Network Printer Settings GoType.
type Network Printer Settings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ServerIp string `json:"server_ip" db:"server_ip"`
	Port int `json:"port" db:"port"`
	ColumnBreak4 string `json:"column_break_4" db:"column_break_4"`
	PrinterName string `json:"printer_name" db:"printer_name"`
}
