// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Email Template is the type-safe Go struct generated from the Email Template GoType.
type Email Template struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Subject string `json:"subject" db:"subject"`
	Response string `json:"response" db:"response"`
	SectionBreak4 string `json:"section_break_4" db:"section_break_4"`
	EmailReplyHelp string `json:"email_reply_help" db:"email_reply_help"`
	UseHtml int `json:"use_html" db:"use_html"`
	ResponseHtml string `json:"response_html" db:"response_html"`
}
