// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// DocShare is the type-safe Go struct generated from the DocShare GoType.
type DocShare struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	User string `json:"user" db:"user"`
	ShareDoctype string `json:"share_doctype" db:"share_doctype"`
	ShareName string `json:"share_name" db:"share_name"`
	Read int `json:"read" db:"read"`
	Write int `json:"write" db:"write"`
	Share int `json:"share" db:"share"`
	Everyone int `json:"everyone" db:"everyone"`
	NotifyByEmail int `json:"notify_by_email" db:"notify_by_email"`
	Submit int `json:"submit" db:"submit"`
}
