// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Security Settings Contact is the type-safe Go struct generated from the Security Settings Contact GoType.
type Security Settings Contact struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Type string `json:"type" db:"type"`
	Contact string `json:"contact" db:"contact"`
}
