// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Report Filter is the type-safe Go struct generated from the Report Filter GoType.
type Report Filter struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Fieldname string `json:"fieldname" db:"fieldname"`
	Label string `json:"label" db:"label"`
	Fieldtype string `json:"fieldtype" db:"fieldtype"`
	Mandatory int `json:"mandatory" db:"mandatory"`
	Options string `json:"options" db:"options"`
	WildcardFilter int `json:"wildcard_filter" db:"wildcard_filter"`
	Default string `json:"default" db:"default"`
	ColumnBreakUrrx string `json:"column_break_urrx" db:"column_break_urrx"`
}
