// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Email Group Member is the type-safe Go struct generated from the Email Group Member GoType.
type Email Group Member struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	EmailGroup string `json:"email_group" db:"email_group"`
	Email string `json:"email" db:"email"`
	Unsubscribed int `json:"unsubscribed" db:"unsubscribed"`
}
