// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Custom DocPerm is the type-safe Go struct generated from the Custom DocPerm GoType.
type Custom DocPerm struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	RoleAndLevel string `json:"role_and_level" db:"role_and_level"`
	Role string `json:"role" db:"role"`
	IfOwner int `json:"if_owner" db:"if_owner"`
	ColumnBreak2 string `json:"column_break_2" db:"column_break_2"`
	Permlevel int `json:"permlevel" db:"permlevel"`
	SectionBreak4 string `json:"section_break_4" db:"section_break_4"`
	Read int `json:"read" db:"read"`
	Write int `json:"write" db:"write"`
	Create int `json:"create" db:"create"`
	Delete int `json:"delete" db:"delete"`
	ColumnBreak8 string `json:"column_break_8" db:"column_break_8"`
	Submit int `json:"submit" db:"submit"`
	Cancel int `json:"cancel" db:"cancel"`
	Amend int `json:"amend" db:"amend"`
	Mask int `json:"mask" db:"mask"`
	AdditionalPermissions string `json:"additional_permissions" db:"additional_permissions"`
	Report int `json:"report" db:"report"`
	Export int `json:"export" db:"export"`
	Import int `json:"import" db:"import"`
	ColumnBreak19 string `json:"column_break_19" db:"column_break_19"`
	Share int `json:"share" db:"share"`
	Print int `json:"print" db:"print"`
	Email int `json:"email" db:"email"`
	Parent string `json:"parent" db:"parent"`
	Select int `json:"select" db:"select"`
}
