// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Auto Repeat User is the type-safe Go struct generated from the Auto Repeat User GoType.
type Auto Repeat User struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	User string `json:"user" db:"user"`
}
