// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// SystemSettings is the type-safe Go struct generated from the SystemSettings GoType.
type SystemSettings struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	AppName string `json:"app_name" db:"app_name"`
	Language string `json:"language" db:"language"`
	TimeZone string `json:"time_zone" db:"time_zone"`
	DateFormat string `json:"date_format" db:"date_format"`
	TimeFormat string `json:"time_format" db:"time_format"`
	SessionExpiry string `json:"session_expiry" db:"session_expiry"`
	EnableTwoFactorAuth int `json:"enable_two_factor_auth" db:"enable_two_factor_auth"`
}
