// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Notification Subscribed Document is the type-safe Go struct generated from the Notification Subscribed Document GoType.
type Notification Subscribed Document struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Document string `json:"document" db:"document"`
}
