// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Data Import is the type-safe Go struct generated from the Data Import GoType.
type Data Import struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ImportType string `json:"import_type" db:"import_type"`
	ImportFile string `json:"import_file" db:"import_file"`
	ImportPreview string `json:"import_preview" db:"import_preview"`
	SectionImportPreview string `json:"section_import_preview" db:"section_import_preview"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	TemplateOptions string `json:"template_options" db:"template_options"`
	ImportLogSection string `json:"import_log_section" db:"import_log_section"`
	ImportLogPreview string `json:"import_log_preview" db:"import_log_preview"`
	Status string `json:"status" db:"status"`
	TemplateWarnings string `json:"template_warnings" db:"template_warnings"`
	SubmitAfterImport int `json:"submit_after_import" db:"submit_after_import"`
	ImportWarningsSection string `json:"import_warnings_section" db:"import_warnings_section"`
	ImportWarnings string `json:"import_warnings" db:"import_warnings"`
	DownloadTemplate string `json:"download_template" db:"download_template"`
	MuteEmails int `json:"mute_emails" db:"mute_emails"`
	ShowFailedLogs int `json:"show_failed_logs" db:"show_failed_logs"`
	Html5 string `json:"html_5" db:"html_5"`
	GoogleSheetsUrl string `json:"google_sheets_url" db:"google_sheets_url"`
	RefreshGoogleSheet string `json:"refresh_google_sheet" db:"refresh_google_sheet"`
	PayloadCount int `json:"payload_count" db:"payload_count"`
	DelimiterOptions string `json:"delimiter_options" db:"delimiter_options"`
	CustomDelimiters int `json:"custom_delimiters" db:"custom_delimiters"`
	UseCsvSniffer int `json:"use_csv_sniffer" db:"use_csv_sniffer"`
}
