// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Integration Request is the type-safe Go struct generated from the Integration Request GoType.
type Integration Request struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	IntegrationRequestService string `json:"integration_request_service" db:"integration_request_service"`
	Status string `json:"status" db:"status"`
	Data string `json:"data" db:"data"`
	Output string `json:"output" db:"output"`
	Error string `json:"error" db:"error"`
	ReferenceDoctype string `json:"reference_doctype" db:"reference_doctype"`
	ReferenceDocname string `json:"reference_docname" db:"reference_docname"`
	IsRemoteRequest int `json:"is_remote_request" db:"is_remote_request"`
	RequestDescription string `json:"request_description" db:"request_description"`
	RequestId string `json:"request_id" db:"request_id"`
	ColumnBreak5 string `json:"column_break_5" db:"column_break_5"`
	SectionBreak8 string `json:"section_break_8" db:"section_break_8"`
	Url string `json:"url" db:"url"`
	ResponseSection string `json:"response_section" db:"response_section"`
	ReferenceSection string `json:"reference_section" db:"reference_section"`
	ColumnBreak16 string `json:"column_break_16" db:"column_break_16"`
	RequestHeaders string `json:"request_headers" db:"request_headers"`
	ResponseHeaders string `json:"response_headers" db:"response_headers"`
}
