// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Scheduler Event is the type-safe Go struct generated from the Scheduler Event GoType.
type Scheduler Event struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	ScheduledAgainst string `json:"scheduled_against" db:"scheduled_against"`
	Method string `json:"method" db:"method"`
}
