// Code generated by GoFra. DO NOT EDIT.
package gotypes

import "time"

// Route History is the type-safe Go struct generated from the Route History GoType.
type Route History struct {
	Name     string    `json:"name"     db:"name"`
	Creation time.Time `json:"creation" db:"creation"`
	Modified time.Time `json:"modified" db:"modified"`
	Owner    string    `json:"owner"    db:"owner"`
	Route string `json:"route" db:"route"`
	User string `json:"user" db:"user"`
}
